/**
 * AI Output Certification — provenance, quality, and review metadata
 * for every AI-generated document in Subsumio.
 *
 * This provides a unified certification record that can be:
 * - Embedded in brain page frontmatter
 * - Rendered as a visible stamp on documents
 * - Exported with PDFs/emails
 * - Audited for compliance (EU AI Act Art. 50, GoBD)
 */

import { AI_NOTICE, AI_BADGE_LABEL } from "@/lib/ai-act";
import { getModelById, type ModelEntry } from "@/lib/model-config";

export type CertificationStatus =
  | "pending" // AI generated, awaiting attorney review
  | "reviewed" // Attorney reviewed and approved
  | "rejected" // Attorney reviewed and rejected
  | "certified" // Fully certified (reviewed + signed off)
  | "superseded"; // Replaced by a newer version

export interface AICertification {
  /** Unique certification ID */
  id: string;
  /** Status of the certification */
  status: CertificationStatus;
  /** Model that generated this output */
  model?: {
    id: string;
    name: string;
    provider: string;
    dataResidency?: "eu" | "non_eu";
  };
  /** Pipeline metadata (if generated by pipeline) */
  pipeline?: {
    caseSlug: string;
    layer?: number;
    layerName?: string;
    totalScore?: number;
    ensembleRecommendation?: string;
    retryCount?: number;
  };
  /** Specialist that generated this output (if applicable) */
  specialist?: string;
  /** Timestamp of generation */
  generatedAt: string;
  /** Timestamp of review (if reviewed) */
  reviewedAt?: string;
  /** Reviewer user ID (if reviewed) */
  reviewedBy?: string;
  /** Reviewer name (if reviewed) */
  reviewerName?: string;
  /** Review notes (if reviewed) */
  reviewNotes?: string;
  /** Content hash for integrity verification */
  contentHash?: string;
  /** AI Act Art. 50 notice */
  aiNotice: string;
  /** AI Act Art. 50 badge label */
  aiBadgeLabel: string;
  /** Confidence score (0-100) */
  confidenceScore?: number;
  /** Whether citations were verified against corpus */
  citationsVerified?: boolean;
  /** Number of verified citations */
  verifiedCitationCount?: number;
  /** Number of unverified citations */
  unverifiedCitationCount?: number;
  /** Jurisdiction */
  jurisdiction?: string;
  /** Version of the pipeline/specialist that generated this */
  version?: string;
}

/**
 * Create a certification record from frontmatter and optional model info.
 */
export function createCertification(
  frontmatter: Record<string, unknown>,
  options?: {
    content?: string;
    modelId?: string;
    caseSlug?: string;
    layer?: number;
    layerName?: string;
  }
): AICertification {
  const modelId = options?.modelId ?? String(frontmatter.model_id ?? frontmatter.model ?? "");
  const model = modelId ? getModelById(modelId) : undefined;

  const totalScore =
    typeof frontmatter.total_score === "number" ? frontmatter.total_score : undefined;

  const status = String(
    frontmatter.certification_status ?? frontmatter.review_status ?? "pending"
  ) as CertificationStatus;

  return {
    id: String(
      frontmatter.certification_id ?? `cert-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`
    ),
    status,
    model: model
      ? {
          id: model.id,
          name: model.name,
          provider: model.provider,
          dataResidency: model.dataResidency,
        }
      : modelId
        ? {
            id: modelId,
            name: modelId,
            provider: String(frontmatter.model_provider ?? "unknown"),
          }
        : undefined,
    pipeline: options?.caseSlug
      ? {
          caseSlug: options.caseSlug,
          layer:
            options?.layer ??
            (typeof frontmatter.current_layer === "number" ? frontmatter.current_layer : undefined),
          layerName: options?.layerName,
          totalScore,
          ensembleRecommendation:
            typeof frontmatter.ensemble_recommendation === "string"
              ? frontmatter.ensemble_recommendation
              : undefined,
          retryCount:
            typeof frontmatter.retry_count === "number" ? frontmatter.retry_count : undefined,
        }
      : undefined,
    specialist: typeof frontmatter.specialist === "string" ? frontmatter.specialist : undefined,
    generatedAt: String(
      frontmatter.generated_at ?? frontmatter.created_at ?? new Date().toISOString()
    ),
    reviewedAt:
      typeof frontmatter.attorney_reviewed_at === "string"
        ? frontmatter.attorney_reviewed_at
        : typeof frontmatter.reviewed_at === "string"
          ? frontmatter.reviewed_at
          : undefined,
    reviewedBy: typeof frontmatter.reviewed_by === "string" ? frontmatter.reviewed_by : undefined,
    reviewerName:
      typeof frontmatter.reviewer_name === "string" ? frontmatter.reviewer_name : undefined,
    reviewNotes:
      typeof frontmatter.review_notes === "string" ? frontmatter.review_notes : undefined,
    contentHash:
      typeof frontmatter.content_hash === "string" ? frontmatter.content_hash : undefined,
    aiNotice: AI_NOTICE,
    aiBadgeLabel: AI_BADGE_LABEL,
    confidenceScore: totalScore,
    citationsVerified: frontmatter.citations_verified === true,
    verifiedCitationCount:
      typeof frontmatter.citations_verified_count === "number"
        ? frontmatter.citations_verified_count
        : undefined,
    unverifiedCitationCount:
      typeof frontmatter.citations_unverified_count === "number"
        ? frontmatter.citations_unverified_count
        : undefined,
    jurisdiction:
      typeof frontmatter.jurisdiction === "string" ? frontmatter.jurisdiction : undefined,
    version:
      typeof frontmatter.pipeline_version === "string" ? frontmatter.pipeline_version : undefined,
  };
}

/**
 * Convert a certification record to frontmatter for persistence.
 */
export function certificationToFrontmatter(cert: AICertification): Record<string, unknown> {
  return {
    certification_id: cert.id,
    certification_status: cert.status,
    model_id: cert.model?.id,
    model_provider: cert.model?.provider,
    specialist: cert.specialist,
    generated_at: cert.generatedAt,
    attorney_reviewed_at: cert.reviewedAt,
    reviewed_by: cert.reviewedBy,
    reviewer_name: cert.reviewerName,
    review_notes: cert.reviewNotes,
    content_hash: cert.contentHash,
    ai_generated: true,
    ai_notice: cert.aiNotice,
    total_score: cert.confidenceScore,
    citations_verified: cert.citationsVerified,
    citations_verified_count: cert.verifiedCitationCount,
    citations_unverified_count: cert.unverifiedCitationCount,
    jurisdiction: cert.jurisdiction,
    pipeline_version: cert.version,
  };
}

/**
 * Compute a simple hash of content for integrity verification.
 * Uses SubtleCrypto if available, falls back to a simple hash.
 */
export async function computeContentHash(content: string): Promise<string> {
  if (typeof crypto !== "undefined" && crypto.subtle) {
    const encoder = new TextEncoder();
    const data = encoder.encode(content);
    const hashBuffer = await crypto.subtle.digest("SHA-256", data);
    const hashArray = Array.from(new Uint8Array(hashBuffer));
    return hashArray
      .map((b) => b.toString(16).padStart(2, "0"))
      .join("")
      .slice(0, 16);
  }
  // Fallback: simple djb2 hash
  let hash = 5381;
  for (let i = 0; i < content.length; i++) {
    hash = (hash << 5) + hash + content.charCodeAt(i);
  }
  return Math.abs(hash).toString(16).slice(0, 16);
}

/**
 * Status display configuration.
 */
export const CERT_STATUS_CONFIG: Record<
  CertificationStatus,
  { label: string; labelEn: string; color: string; bgColor: string; borderColor: string }
> = {
  pending: {
    label: "Prüfung ausständig",
    labelEn: "Review pending",
    color: "text-amber-600",
    bgColor: "bg-amber-500/10",
    borderColor: "border-amber-500/30",
  },
  reviewed: {
    label: "Geprüft",
    labelEn: "Reviewed",
    color: "text-emerald-600",
    bgColor: "bg-emerald-500/10",
    borderColor: "border-emerald-500/30",
  },
  rejected: {
    label: "Abgelehnt",
    labelEn: "Rejected",
    color: "text-red-600",
    bgColor: "bg-red-500/10",
    borderColor: "border-red-500/30",
  },
  certified: {
    label: "Zertifiziert",
    labelEn: "Certified",
    color: "text-emerald-700",
    bgColor: "bg-emerald-500/15",
    borderColor: "border-emerald-500/40",
  },
  superseded: {
    label: "Ersetzt",
    labelEn: "Superseded",
    color: "text-[color:var(--ds-text-muted)]",
    bgColor: "bg-[color:var(--ds-hover)]",
    borderColor: "border-[color:var(--ds-border)]",
  },
};
