/**
 * Server-side corpus metadata facade.
 * The generated data stays in JSON so SWC does not parse a 7,800-entry
 * TypeScript object during every Next.js production build.
 *
 * AUTO-GENERATED by scripts/generate-corpus-meta.ts
 * Generated: 2026-09-12
 * Entries: 7800
 * DO NOT EDIT MANUALLY — run: bun scripts/generate-corpus-meta.ts
 */

import { readFileSync } from "node:fs";
import { join } from "node:path";

export interface CorpusMetaEntry {
  jurisdiction: "at" | "de" | "ch" | "eu";
  label: string;
  file: string;
  type?: "statute" | "state_treaty" | "state_law";
}

const corpusMetaPath = join(process.cwd(), "src", "lib", "corpus-meta.json");
export const CORPUS_META = JSON.parse(readFileSync(corpusMetaPath, "utf8")) as Record<
  string,
  CorpusMetaEntry
>;
