/**
 * AT legal retrieval gold set — PENDING REVIEW (draft questions).
 *
 * Generated by server/scripts/draft-gold-questions.ts from the real AT
 * statute corpus. Every § has been validated against law-corpus-split/at/.
 *
 * Review workflow:
 *   1. Review each entry for legal accuracy and query quality.
 *   2. Set reviewed_by + reviewed_at for approved entries.
 *   3. Move approved entries to corpus.ts (LEGAL_AT_GOLD).
 *
 * DO NOT move entries to the gold set without reviewed_by + reviewed_at.
 */

import type { NamedThingQuestion } from "../../../../src/eval/retrieval-quality/harness.ts";

interface Ref {
  jur: "at" | "de";
  file: string;
  abbr: string;
  ref: string;
}

interface DraftEntry {
  query: string;
  family: NamedThingQuestion["family"];
  at: Ref;
  de?: Ref;
  domain: string;
  status: "draft" | "reviewed";
  reviewed_by?: string;
  reviewed_at?: string;
}

const A = (file: string, abbr: string, ref: string): Ref => ({ jur: "at", file, abbr, ref });
const D = (file: string, abbr: string, ref: string): Ref => ({ jur: "de", file, abbr, ref });

export const LEGAL_AT_PENDING: DraftEntry[] = [
  // ── Zivilrecht/Schadenersatz (25 questions) ────────────────────────────
  { query: "inbegriff gesetze wodurch", family: "keyword", at: A("at/abgb.md", "abgb", "1"), de: D("de/bgb.md", "bgb", "79a"), domain: "Zivilrecht/Schadenersatz", status: "draft" },
  { query: "allen minderjährige kind", family: "keyword", at: A("at/abgb.md", "abgb", "138"), de: D("de/bgb.md", "bgb", "11"), domain: "Zivilrecht/Schadenersatz", status: "draft" },
  { query: "eltern vereinbarungen obsorge", family: "keyword", at: A("at/abgb.md", "abgb", "190"), de: D("de/bgb.md", "bgb", "202"), domain: "Zivilrecht/Schadenersatz", status: "draft" },
  { query: "person erwachsenenvertreter verfügung", family: "keyword", at: A("at/abgb.md", "abgb", "244"), de: D("de/bgb.md", "bgb", "13"), domain: "Zivilrecht/Schadenersatz", status: "draft" },
  { query: "getreide holz viehfutter ABGB", family: "code-scoped", at: A("at/abgb.md", "abgb", "296"), domain: "Zivilrecht/Schadenersatz", status: "draft" },
  { query: "bloße inhaber mehreren Eigentum Besitz", family: "keyword", at: A("at/abgb.md", "abgb", "348"), de: D("de/bgb.md", "bgb", "28"), domain: "Zivilrecht/Schadenersatz", status: "draft" },
  { query: "Frist finden arbeitsleute zufälliger", family: "concept", at: A("at/abgb.md", "abgb", "401"), de: D("de/bgb.md", "bgb", "40"), domain: "Zivilrecht/Schadenersatz", status: "draft" },
  { query: "pfandinhaber pfand weit", family: "keyword", at: A("at/abgb.md", "abgb", "454"), de: D("de/bgb.md", "bgb", "12"), domain: "Zivilrecht/Schadenersatz", status: "draft" },
  { query: "anzahl triebviehes während", family: "keyword", at: A("at/abgb.md", "abgb", "500"), de: D("de/bgb.md", "bgb", "160"), domain: "Zivilrecht/Schadenersatz", status: "draft" },
  { query: "verstorbene mehrere personen ABGB", family: "code-scoped", at: A("at/abgb.md", "abgb", "555"), de: D("de/bgb.md", "bgb", "2032"), domain: "Zivilrecht/Schadenersatz", status: "draft" },
  { query: "vermächtnisnehmer vollständigen erfüllung", family: "keyword", at: A("at/abgb.md", "abgb", "650"), de: D("de/bgb.md", "bgb", "341"), domain: "Zivilrecht/Schadenersatz", status: "draft" },
  { query: "anordnung verstorbenen dass", family: "keyword", at: A("at/abgb.md", "abgb", "712"), de: D("de/bgb.md", "bgb", "1981"), domain: "Zivilrecht/Schadenersatz", status: "draft" },
  { query: "letztwillig verfügende stundung", family: "keyword", at: A("at/abgb.md", "abgb", "766"), de: D("de/bgb.md", "bgb", "468"), domain: "Zivilrecht/Schadenersatz", status: "draft" },
  { query: "verschiedenheit quellen denen Eigentum Besitz", family: "keyword", at: A("at/abgb.md", "abgb", "826"), de: D("de/bgb.md", "bgb", "312c"), domain: "Zivilrecht/Schadenersatz", status: "draft" },
  { query: "jedem falle derjenige ABGB", family: "code-scoped", at: A("at/abgb.md", "abgb", "874"), de: D("de/bgb.md", "bgb", "108"), domain: "Zivilrecht/Schadenersatz", status: "draft" },
  { query: "Gewährleistung Mängel verordnung bestimmt inwiefern", family: "concept", at: A("at/abgb.md", "abgb", "925"), de: D("de/bgb.md", "bgb", "2"), domain: "Zivilrecht/Schadenersatz", status: "draft" },
  { query: "streite dauer gebrauches Beweis", family: "keyword", at: A("at/abgb.md", "abgb", "975"), de: D("de/bgb.md", "bgb", "194"), domain: "Zivilrecht/Schadenersatz", status: "draft" },
  { query: "fremde geschäfte bloß Gesellschaftsrecht", family: "keyword", at: A("at/abgb.md", "abgb", "1037"), de: D("de/bgb.md", "bgb", "49"), domain: "Zivilrecht/Schadenersatz", status: "draft" },
  { query: "Vertrag vertrag wodurch jemand", family: "concept", at: A("at/abgb.md", "abgb", "1090"), de: D("de/bgb.md", "bgb", "2302"), domain: "Zivilrecht/Schadenersatz", status: "draft" },
  { query: "liegt freies dienstverhältnis ABGB", family: "code-scoped", at: A("at/abgb.md", "abgb", "1164a"), de: D("de/bgb.md", "bgb", "517"), domain: "Zivilrecht/Schadenersatz", status: "draft" },
  { query: "verbleibt gesellschafter erlischt Gesellschaftsrecht", family: "keyword", at: A("at/abgb.md", "abgb", "1215"), de: D("de/bgb.md", "bgb", "707"), domain: "Zivilrecht/Schadenersatz", status: "draft" },
  { query: "schade heißt nachtheil", family: "keyword", at: A("at/abgb.md", "abgb", "1293"), de: D("de/bgb.md", "bgb", "51"), domain: "Zivilrecht/Schadenersatz", status: "draft" },
  { query: "sowohl personenrechte sachenrechte", family: "keyword", at: A("at/abgb.md", "abgb", "1342"), de: D("de/bgb.md", "bgb", "594d"), domain: "Zivilrecht/Schadenersatz", status: "draft" },
  { query: "abtretungsvertrag entsteht zwischen Vertrag", family: "keyword", at: A("at/abgb.md", "abgb", "1395"), de: D("de/bgb.md", "bgb", "68"), domain: "Zivilrecht/Schadenersatz", status: "draft" },
  { query: "rechte verbindlichkeiten öffentlichen ABGB", family: "code-scoped", at: A("at/abgb.md", "abgb", "1446"), de: D("de/bgb.md", "bgb", "1487"), domain: "Zivilrecht/Schadenersatz", status: "draft" },

  // ── Mietrecht (15 questions) ────────────────────────────
  { query: "bundesgesetz gilt miete", family: "keyword", at: A("at/mrg.md", "mrg", "1"), de: D("de/bgb.md", "bgb", "24"), domain: "Mietrecht", status: "draft" },
  { query: "hauptmieter wohnung verläßt", family: "keyword", at: A("at/mrg.md", "mrg", "12"), de: D("de/bgb.md", "bgb", "516"), domain: "Mietrecht", status: "draft" },
  { query: "finden kosten vermieter", family: "keyword", at: A("at/mrg.md", "mrg", "18"), de: D("de/bgb.md", "bgb", "40"), domain: "Mietrecht", status: "draft" },
  { query: "stellt vermieter hauptmieter", family: "keyword", at: A("at/mrg.md", "mrg", "25"), de: D("de/bgb.md", "bgb", "535"), domain: "Mietrecht", status: "draft" },
  { query: "räumung innezuhalten räumenden MRG", family: "code-scoped", at: A("at/mrg.md", "mrg", "34a"), de: D("de/bgb.md", "bgb", "540"), domain: "Mietrecht", status: "draft" },
  { query: "insoweit folgenden nichts", family: "keyword", at: A("at/mrg.md", "mrg", "43"), de: D("de/bgb.md", "bgb", "1697a"), domain: "Mietrecht", status: "draft" },
  { query: "änderungen bundesgesetz bgbl", family: "keyword", at: A("at/mrg.md", "mrg", "49b"), de: D("de/bgb.md", "bgb", "71"), domain: "Mietrecht", status: "draft" },
  { query: "gemeinden zeitpunkt inkrafttretens", family: "keyword", at: A("at/mrg.md", "mrg", "50"), de: D("de/bgb.md", "bgb", "85"), domain: "Mietrecht", status: "draft" },
  { query: "Eigentum Besitz bundesgesetz regelt rechtsform", family: "concept", at: A("at/weg.md", "weg", "1"), de: D("de/bgb.md", "bgb", "85"), domain: "Mietrecht", status: "draft" },
  { query: "gerichtliche nutzwertfestsetzung fällen Eigentum Besitz", family: "keyword", at: A("at/weg.md", "weg", "10"), de: D("de/bgb.md", "bgb", "36"), domain: "Mietrecht", status: "draft" },
  { query: "eigentümergemeinschaft natürliche juristische Zuständigkeit Gericht", family: "keyword", at: A("at/weg.md", "weg", "19"), de: D("de/bgb.md", "bgb", "14"), domain: "Mietrecht", status: "draft" },
  { query: "angelegenheiten ordentlichen verwaltung", family: "keyword", at: A("at/weg.md", "weg", "28"), de: D("de/bgb.md", "bgb", "32"), domain: "Mietrecht", status: "draft" },
  { query: "eintragung anmerkung einräumung WEG", family: "code-scoped", at: A("at/weg.md", "weg", "37"), de: D("de/bgb.md", "bgb", "55"), domain: "Mietrecht", status: "draft" },
  { query: "dreijährige frist beginnt Eigentum Besitz", family: "keyword", at: A("at/weg.md", "weg", "46"), de: D("de/bgb.md", "bgb", "1"), domain: "Mietrecht", status: "draft" },
  { query: "Eigentum Besitz wohnungseigentumsgesetz bgbl zuletzt", family: "concept", at: A("at/weg.md", "weg", "55"), de: D("de/bgb.md", "bgb", "880"), domain: "Mietrecht", status: "draft" },

  // ── Arbeitsrecht (20 questions) ────────────────────────────
  { query: "Arbeitsrecht bundesgesetz gilt dienstverhältnis", family: "concept", at: A("at/angg.md", "angg", "1"), domain: "Arbeitsrecht", status: "draft" },
  { query: "angestellte während dienstverhinderung Arbeitsrecht", family: "keyword", at: A("at/angg.md", "angg", "9"), de: D("de/betrvg.md", "betrvg", "39"), domain: "Arbeitsrecht", status: "draft" },
  { query: "falls angestellte anspruch Frist", family: "keyword", at: A("at/angg.md", "angg", "16"), de: D("de/betrvg.md", "betrvg", "105"), domain: "Arbeitsrecht", status: "draft" },
  { query: "Arbeitsrecht anspruch abfertigung besteht", family: "concept", at: A("at/angg.md", "angg", "23a"), de: D("de/betrvg.md", "betrvg", "1"), domain: "Arbeitsrecht", status: "draft" },
  { query: "dienstgeber wichtigen grund ANGG", family: "code-scoped", at: A("at/angg.md", "angg", "31"), domain: "Arbeitsrecht", status: "draft" },
  { query: "Vertrag bestimmungen teiles gelten", family: "concept", at: A("at/arbvg.md", "arbvg", "1"), de: D("de/betrvg.md", "betrvg", "4"), domain: "Arbeitsrecht", status: "draft" },
  { query: "wahlvorstand wahlhandlung leiten", family: "keyword", at: A("at/arbvg.md", "arbvg", "56"), de: D("de/betrvg.md", "betrvg", "18"), domain: "Arbeitsrecht", status: "draft" },
  { query: "betriebsinhaber beabsichtigte vergabe Arbeitsrecht", family: "keyword", at: A("at/arbvg.md", "arbvg", "103"), de: D("de/betrvg.md", "betrvg", "5"), domain: "Arbeitsrecht", status: "draft" },
  { query: "Vertrag bundeseinigungsamt weiters berufen", family: "concept", at: A("at/arbvg.md", "arbvg", "158"), domain: "Arbeitsrecht", status: "draft" },
  { query: "besondere verhandlungsgremium grund ARBVG", family: "code-scoped", at: A("at/arbvg.md", "arbvg", "215"), domain: "Arbeitsrecht", status: "draft" },
  { query: "Vertrag bundesgesetz gilt arbeitsverhältnisse", family: "concept", at: A("at/avrag.md", "avrag", "1"), domain: "Arbeitsrecht", status: "draft" },
  { query: "telearbeit liegt arbeitnehmerin Arbeitsrecht", family: "keyword", at: A("at/avrag.md", "avrag", "2h"), de: D("de/betrvg.md", "betrvg", "5"), domain: "Arbeitsrecht", status: "draft" },
  { query: "arbeitgeber arbeitgeberin arbeitnehmer Arbeitsrecht", family: "keyword", at: A("at/avrag.md", "avrag", "7a"), de: D("de/betrvg.md", "betrvg", "81"), domain: "Arbeitsrecht", status: "draft" },
  { query: "Arbeitsrecht zwischen arbeitgeber arbeitnehmer", family: "concept", at: A("at/avrag.md", "avrag", "14"), de: D("de/betrvg.md", "betrvg", "76"), domain: "Arbeitsrecht", status: "draft" },
  { query: "versicherungsträger gemäß asvg AVRAG", family: "code-scoped", at: A("at/avrag.md", "avrag", "15b"), domain: "Arbeitsrecht", status: "draft" },
  { query: "Arbeitsrecht bestimmungen bundesgesetzes gelten", family: "concept", at: A("at/azg.md", "azg", "1"), de: D("de/betrvg.md", "betrvg", "4"), domain: "Arbeitsrecht", status: "draft" },
  { query: "beträgt gesamtdauer tagesarbeitszeit Arbeitsrecht", family: "keyword", at: A("at/azg.md", "azg", "11"), de: D("de/betrvg.md", "betrvg", "21"), domain: "Arbeitsrecht", status: "draft" },
  { query: "lenkerinnen lenker dürfen", family: "keyword", at: A("at/azg.md", "azg", "15c"), domain: "Arbeitsrecht", status: "draft" },
  { query: "sinne bundesgesetzes zugpersonal", family: "keyword", at: A("at/azg.md", "azg", "18f"), de: D("de/betrvg.md", "betrvg", "5"), domain: "Arbeitsrecht", status: "draft" },
  { query: "rufbereitschaft außerhalb arbeitszeit AZG", family: "code-scoped", at: A("at/azg.md", "azg", "20a"), de: D("de/betrvg.md", "betrvg", "16"), domain: "Arbeitsrecht", status: "draft" },

  // ── Gesellschaftsrecht (20 questions) ────────────────────────────
  { query: "bestimmungen bundesgesetzes können", family: "keyword", at: A("at/ugb.md", "ugb", "1"), de: D("de/hgb.md", "hgb", "142"), domain: "Gesellschaftsrecht", status: "draft" },
  { query: "sowie finden kommanditisten", family: "keyword", at: A("at/ugb.md", "ugb", "165"), domain: "Gesellschaftsrecht", status: "draft" },
  { query: "sobald gesetzlichen voraussetzungen", family: "keyword", at: A("at/ugb.md", "ugb", "274"), de: D("de/hgb.md", "hgb", "19"), domain: "Gesellschaftsrecht", status: "draft" },
  { query: "verpflichtung auslieferung gutes", family: "keyword", at: A("at/ugb.md", "ugb", "444"), de: D("de/hgb.md", "hgb", "443"), domain: "Gesellschaftsrecht", status: "draft" },
  { query: "macht befrachter bezeichneten UGB", family: "code-scoped", at: A("at/ugb.md", "ugb", "581"), de: D("de/hgb.md", "hgb", "364"), domain: "Gesellschaftsrecht", status: "draft" },
  { query: "anspruch vergütung großen", family: "keyword", at: A("at/ugb.md", "ugb", "705"), de: D("de/hgb.md", "hgb", "87"), domain: "Gesellschaftsrecht", status: "draft" },
  { query: "anzeigepflicht versetzt richtig", family: "keyword", at: A("at/ugb.md", "ugb", "811a"), de: D("de/hgb.md", "hgb", "61"), domain: "Gesellschaftsrecht", status: "draft" },
  { query: "Gesellschaftsrecht beschließt gesellschaft gemäß", family: "concept", at: A("at/gmbhg-at.md", "gmbhg", "1"), de: D("de/gmbhg.md", "gmbhg", "4"), domain: "Gesellschaftsrecht", status: "draft" },
  { query: "gesellschaft geschäftsführer gerichtlich Zuständigkeit Gericht", family: "keyword", at: A("at/gmbhg-at.md", "gmbhg", "18"), de: D("de/gmbhg.md", "gmbhg", "35"), domain: "Gesellschaftsrecht", status: "draft" },
  { query: "aufsichtsratsmitglieder können zugleich Gesellschaftsrecht", family: "keyword", at: A("at/gmbhg-at.md", "gmbhg", "30e"), de: D("de/gmbhg.md", "gmbhg", "6"), domain: "Gesellschaftsrecht", status: "draft" },
  { query: "Gesellschaftsrecht klage nichtigerklärung beschlusses", family: "concept", at: A("at/gmbhg-at.md", "gmbhg", "42"), de: D("de/gmbhg.md", "gmbhg", "45"), domain: "Gesellschaftsrecht", status: "draft" },
  { query: "gesellschafter verpflichtet übernommene GMBHG", family: "code-scoped", at: A("at/gmbhg-at.md", "gmbhg", "63"), de: D("de/gmbhg.md", "gmbhg", "20"), domain: "Gesellschaftsrecht", status: "draft" },
  { query: "gesellschafter können stammeinlage Gesellschaftsrecht", family: "keyword", at: A("at/gmbhg-at.md", "gmbhg", "82"), de: D("de/gmbhg.md", "gmbhg", "16"), domain: "Gesellschaftsrecht", status: "draft" },
  { query: "Haftung bundesminister finanzen gesellschaften", family: "concept", at: A("at/gmbhg-at.md", "gmbhg", "104"), de: D("de/gmbhg.md", "gmbhg", "1"), domain: "Gesellschaftsrecht", status: "draft" },
  { query: "bundesgesetz verordnung betreffend", family: "keyword", at: A("at/aktg-at.md", "aktg", "1"), de: D("de/hgb.md", "hgb", "10a"), domain: "Gesellschaftsrecht", status: "draft" },
  { query: "verbindlichkeiten aktiengesellschaft haftet Haftung", family: "keyword", at: A("at/aktg-at.md", "aktg", "48"), de: D("de/hgb.md", "hgb", "171"), domain: "Gesellschaftsrecht", status: "draft" },
  { query: "satzung bestimmten aktionären Gesellschaftsrecht", family: "keyword", at: A("at/aktg-at.md", "aktg", "88"), de: D("de/hgb.md", "hgb", "34"), domain: "Gesellschaftsrecht", status: "draft" },
  { query: "Gesellschaftsrecht ansprüche gesellschaft aktionäre", family: "concept", at: A("at/aktg-at.md", "aktg", "134"), de: D("de/hgb.md", "hgb", "9c"), domain: "Gesellschaftsrecht", status: "draft" },
  { query: "fällen sind gewinn AKTG", family: "code-scoped", at: A("at/aktg-at.md", "aktg", "190"), de: D("de/hgb.md", "hgb", "275"), domain: "Gesellschaftsrecht", status: "draft" },
  { query: "entscheidung antrag gemäß Zuständigkeit Gericht", family: "keyword", at: A("at/aktg-at.md", "aktg", "225i"), de: D("de/hgb.md", "hgb", "139"), domain: "Gesellschaftsrecht", status: "draft" },

  // ── Insolvenzrecht (15 questions) ────────────────────────────
  { query: "Insolvenz artikel bundesgesetzes treten", family: "concept", at: A("at/io.md", "io", "1"), de: D("de/inso.md", "inso", "4"), domain: "Insolvenzrecht", status: "draft" },
  { query: "aufrechnung unzulässig insolvenzgläubiger Insolvenz", family: "keyword", at: A("at/io.md", "io", "20"), de: D("de/inso.md", "inso", "96"), domain: "Insolvenzrecht", status: "draft" },
  { query: "dritte personen sachen Schadenersatz", family: "keyword", at: A("at/io.md", "io", "40"), de: D("de/inso.md", "inso", "12"), domain: "Insolvenzrecht", status: "draft" },
  { query: "Insolvenz eröffnung insolvenzverfahrens eingetragene", family: "concept", at: A("at/io.md", "io", "67"), de: D("de/inso.md", "inso", "3d"), domain: "Insolvenzrecht", status: "draft" },
  { query: "insolvenzverwalter schuldner gläubigern IO", family: "code-scoped", at: A("at/io.md", "io", "80b"), de: D("de/inso.md", "inso", "269a"), domain: "Insolvenzrecht", status: "draft" },
  { query: "sachen denen zweifelhaft", family: "keyword", at: A("at/io.md", "io", "97"), de: D("de/inso.md", "inso", "26"), domain: "Insolvenzrecht", status: "draft" },
  { query: "Insolvenz genehmigung gläubigerausschusses insolvenzgerichts", family: "concept", at: A("at/io.md", "io", "117"), de: D("de/inso.md", "inso", "6"), domain: "Insolvenzrecht", status: "draft" },
  { query: "schlußverteilung deshalb aufgeschoben", family: "keyword", at: A("at/io.md", "io", "137"), de: D("de/inso.md", "inso", "196"), domain: "Insolvenzrecht", status: "draft" },
  { query: "rechtskräftig bestätigten sanierungsplan Insolvenz", family: "keyword", at: A("at/io.md", "io", "156"), de: D("de/inso.md", "inso", "257"), domain: "Insolvenzrecht", status: "draft" },
  { query: "sanierungsplan eingetragenen personengesellschaft IO", family: "code-scoped", at: A("at/io.md", "io", "164a"), de: D("de/inso.md", "inso", "3a"), domain: "Insolvenzrecht", status: "draft" },
  { query: "soweit kosten eröffneten Frist", family: "keyword", at: A("at/io.md", "io", "184"), de: D("de/inso.md", "inso", "4a"), domain: "Insolvenzrecht", status: "draft" },
  { query: "vergütung treuhänders beträgt", family: "keyword", at: A("at/io.md", "io", "204"), de: D("de/inso.md", "inso", "293"), domain: "Insolvenzrecht", status: "draft" },
  { query: "Insolvenz verfahren verteilung erlöses", family: "concept", at: A("at/io.md", "io", "220h"), de: D("de/inso.md", "inso", "170"), domain: "Insolvenzrecht", status: "draft" },
  { query: "eröffnung insolvenzverfahrens vermögen Insolvenz", family: "keyword", at: A("at/io.md", "io", "244"), de: D("de/inso.md", "inso", "11"), domain: "Insolvenzrecht", status: "draft" },
  { query: "schuldenberatungszeichen besteht wappen IO", family: "code-scoped", at: A("at/io.md", "io", "268"), de: D("de/inso.md", "inso", "3e"), domain: "Insolvenzrecht", status: "draft" },

  // ── Strafrecht (20 questions) ────────────────────────────
  { query: "Strafe Strafbarkeit strafe vorbeugende maßnahme", family: "concept", at: A("at/stgb-at.md", "stgb", "1"), de: D("de/stgb.md", "stgb", "79"), domain: "Strafrecht", status: "draft" },
  { query: "verwaltungsbehördliche gerichtliche verwahrungshaft Strafe Strafbarkeit", family: "keyword", at: A("at/stgb-at.md", "stgb", "38"), de: D("de/stgb.md", "stgb", "12"), domain: "Strafrecht", status: "draft" },
  { query: "sinn bundesgesetzes unmündig", family: "keyword", at: A("at/stgb-at.md", "stgb", "74"), domain: "Strafrecht", status: "draft" },
  { query: "Strafe Strafbarkeit anderen dessen einwilligung", family: "concept", at: A("at/stgb-at.md", "stgb", "110"), de: D("de/stgb.md", "stgb", "109"), domain: "Strafrecht", status: "draft" },
  { query: "vorsatz verhalten getäuschten STGB", family: "code-scoped", at: A("at/stgb-at.md", "stgb", "146"), de: D("de/stgb.md", "stgb", "108f"), domain: "Strafrecht", status: "draft" },
  { query: "strafe bedrohte handlung Strafe Strafbarkeit", family: "keyword", at: A("at/stgb-at.md", "stgb", "172"), de: D("de/stgb.md", "stgb", "1"), domain: "Strafrecht", status: "draft" },
  { query: "Strafe Strafbarkeit minderjährige person behördlich", family: "concept", at: A("at/stgb-at.md", "stgb", "196"), de: D("de/stgb.md", "stgb", "56d"), domain: "Strafrecht", status: "draft" },
  { query: "nachgemachtes verfälschtes geld", family: "keyword", at: A("at/stgb-at.md", "stgb", "236"), de: D("de/stgb.md", "stgb", "146"), domain: "Strafrecht", status: "draft" },
  { query: "wahl stimmberechtigt namens Strafe Strafbarkeit", family: "keyword", at: A("at/stgb-at.md", "stgb", "266"), de: D("de/stgb.md", "stgb", "7"), domain: "Strafrecht", status: "draft" },
  { query: "behörde entgegennahme anzeigen STGB", family: "code-scoped", at: A("at/stgb-at.md", "stgb", "298"), de: D("de/stgb.md", "stgb", "164"), domain: "Strafrecht", status: "draft" },
  { query: "strafprozessordnung regelt verfahren", family: "keyword", at: A("at/stpo-at.md", "stpo", "1"), de: D("de/stpo.md", "stpo", "110d"), domain: "Strafrecht", status: "draft" },
  { query: "bundesminister justiz wahrnehmung Zuständigkeit Gericht", family: "keyword", at: A("at/stpo-at.md", "stpo", "47a"), de: D("de/stpo.md", "stpo", "492"), domain: "Strafrecht", status: "draft" },
  { query: "ausdrücklicher information vernommenen", family: "keyword", at: A("at/stpo-at.md", "stpo", "97"), de: D("de/stpo.md", "stpo", "3"), domain: "Strafrecht", status: "draft" },
  { query: "Strafe Strafbarkeit beschlagnahme briefen zulässig", family: "concept", at: A("at/stpo-at.md", "stpo", "135"), de: D("de/stpo.md", "stpo", "99"), domain: "Strafrecht", status: "draft" },
  { query: "beschuldigte sollen gemeinschaft STPO", family: "code-scoped", at: A("at/stpo-at.md", "stpo", "185"), de: D("de/stpo.md", "stpo", "81c"), domain: "Strafrecht", status: "draft" },
  { query: "grund ergehenden beschlüsse Strafe Strafbarkeit", family: "keyword", at: A("at/stpo-at.md", "stpo", "237"), de: D("de/stpo.md", "stpo", "20"), domain: "Strafrecht", status: "draft" },
  { query: "beschwerdeführer recht binnen", family: "keyword", at: A("at/stpo-at.md", "stpo", "285"), de: D("de/stpo.md", "stpo", "43"), domain: "Strafrecht", status: "draft" },
  { query: "abstimmung geschworenen sonstiger", family: "keyword", at: A("at/stpo-at.md", "stpo", "329"), de: D("de/stpo.md", "stpo", "263"), domain: "Strafrecht", status: "draft" },
  { query: "kosten strafverfahrens kostenersatze", family: "keyword", at: A("at/stpo-at.md", "stpo", "381"), de: D("de/stpo.md", "stpo", "177"), domain: "Strafrecht", status: "draft" },
  { query: "bezirksgericht ansicht dass STPO", family: "code-scoped", at: A("at/stpo-at.md", "stpo", "450"), de: D("de/stpo.md", "stpo", "148a"), domain: "Strafrecht", status: "draft" },

  // ── Zivilverfahren/Exekution (15 questions) ────────────────────────────
  { query: "Zuständigkeit Gericht person insoweit fähig", family: "concept", at: A("at/zpo-at.md", "zpo", "1"), de: D("de/zpo.md", "zpo", "12"), domain: "Zivilverfahren/Exekution", status: "draft" },
  { query: "tagsatzung beginnt aufrufe", family: "keyword", at: A("at/zpo-at.md", "zpo", "133"), de: D("de/zpo.md", "zpo", "220"), domain: "Zivilverfahren/Exekution", status: "draft" },
  { query: "thatsächliche behauptung glaubhaft Beweis", family: "keyword", at: A("at/zpo-at.md", "zpo", "274"), de: D("de/zpo.md", "zpo", "294"), domain: "Zivilverfahren/Exekution", status: "draft" },
  { query: "Zuständigkeit Gericht rechtsstreite anspruch grund", family: "concept", at: A("at/zpo-at.md", "zpo", "393"), de: D("de/zpo.md", "zpo", "304"), domain: "Zivilverfahren/Exekution", status: "draft" },
  { query: "beschlüsse bescheide sofern ZPO", family: "code-scoped", at: A("at/zpo-at.md", "zpo", "514"), de: D("de/zpo.md", "zpo", "1"), domain: "Zivilverfahren/Exekution", status: "draft" },
  { query: "Zuständigkeit Gericht durchsetzung geldforderungen sowie", family: "concept", at: A("at/eo.md", "eo", "1"), de: D("de/zpo.md", "zpo", "226"), domain: "Zivilverfahren/Exekution", status: "draft" },
  { query: "verwalter zugleich rechnungslegung Zuständigkeit Gericht", family: "keyword", at: A("at/eo.md", "eo", "82c"), de: D("de/zpo.md", "zpo", "94"), domain: "Zivilverfahren/Exekution", status: "draft" },
  { query: "gemäß angeordnete verwaltung Zuständigkeit Gericht", family: "keyword", at: A("at/eo.md", "eo", "192"), de: D("de/zpo.md", "zpo", "748"), domain: "Zivilverfahren/Exekution", status: "draft" },
  { query: "Zuständigkeit Gericht gepfändeten gegenstände überstellung", family: "concept", at: A("at/eo.md", "eo", "279a"), de: D("de/zpo.md", "zpo", "814"), domain: "Zivilverfahren/Exekution", status: "draft" },
  { query: "bewilligung einstweiligen verfügung EO", family: "code-scoped", at: A("at/eo.md", "eo", "397"), de: D("de/zpo.md", "zpo", "123"), domain: "Zivilverfahren/Exekution", status: "draft" },
  { query: "soweit folgenden nichts", family: "keyword", at: A("at/au-strg.md", "au-strg", "1"), de: D("de/zpo.md", "zpo", "1052"), domain: "Zivilverfahren/Exekution", status: "draft" },
  { query: "gericht erster instanz Frist", family: "keyword", at: A("at/au-strg.md", "au-strg", "51"), de: D("de/zpo.md", "zpo", "3"), domain: "Zivilverfahren/Exekution", status: "draft" },
  { query: "anerkennung entscheidung selbständigen", family: "keyword", at: A("at/au-strg.md", "au-strg", "98"), de: D("de/zpo.md", "zpo", "37"), domain: "Zivilverfahren/Exekution", status: "draft" },
  { query: "anerkennung entscheidung schutz", family: "keyword", at: A("at/au-strg.md", "au-strg", "131c"), de: D("de/zpo.md", "zpo", "11"), domain: "Zivilverfahren/Exekution", status: "draft" },
  { query: "antrag absonderung verlassenschaft AU-STRG", family: "code-scoped", at: A("at/au-strg.md", "au-strg", "175"), de: D("de/zpo.md", "zpo", "237"), domain: "Zivilverfahren/Exekution", status: "draft" },

  // ── Verwaltung/Verfassung (10 questions) ────────────────────────────
  { query: "Zuständigkeit Gericht sachliche örtliche zuständigkeit", family: "concept", at: A("at/avg.md", "avg", "1"), de: D("de/vwgo.md", "vwgo", "83"), domain: "Verwaltung/Verfassung", status: "draft" },
  { query: "behörde sache möglichst Verwaltungsverfahren", family: "keyword", at: A("at/avg.md", "avg", "18"), de: D("de/vwgo.md", "vwgo", "72"), domain: "Verwaltung/Verfassung", status: "draft" },
  { query: "mündliche verhandlung gemäß", family: "keyword", at: A("at/avg.md", "avg", "42"), de: D("de/vwgo.md", "vwgo", "84"), domain: "Verwaltung/Verfassung", status: "draft" },
  { query: "Beweis aufnahme beweises sachverständige", family: "concept", at: A("at/avg.md", "avg", "52"), de: D("de/vwgo.md", "vwgo", "2"), domain: "Verwaltung/Verfassung", status: "draft" },
  { query: "notwendige ergänzungen ermittlungsverfahrens AVG", family: "code-scoped", at: A("at/avg.md", "avg", "66"), domain: "Verwaltung/Verfassung", status: "draft" },
  { query: "Verfassung österreich demokratische republik", family: "concept", at: A("at/b-vg.md", "b-vg", "1"), de: D("de/gg.md", "gg", "2"), domain: "Verwaltung/Verfassung", status: "draft" },
  { query: "nationalrat seinen beschluß Verfassung", family: "keyword", at: A("at/b-vg.md", "b-vg", "28"), de: D("de/gg.md", "gg", "40"), domain: "Verwaltung/Verfassung", status: "draft" },
  { query: "absatz eins behördliche Verfassung", family: "keyword", at: A("at/b-vg.md", "b-vg", "63"), de: D("de/gg.md", "gg", "16a"), domain: "Verwaltung/Verfassung", status: "draft" },
  { query: "Verfassung absatz eins landtag", family: "concept", at: A("at/b-vg.md", "b-vg", "100"), de: D("de/gg.md", "gg", "42"), domain: "Verwaltung/Verfassung", status: "draft" },
  { query: "absatz eins rechnungshof B-VG", family: "code-scoped", at: A("at/b-vg.md", "b-vg", "127"), de: D("de/gg.md", "gg", "29"), domain: "Verwaltung/Verfassung", status: "draft" },

  // ── Konsumentenschutz/E-Commerce (10 questions) ────────────────────────────
  { query: "hauptstück gilt rechtsgeschäfte", family: "keyword", at: A("at/kschg.md", "kschg", "1"), de: D("de/bgb.md", "bgb", "24"), domain: "Konsumentenschutz/E-Commerce", status: "draft" },
  { query: "mangels anderer vertraglicher Vertrag", family: "keyword", at: A("at/kschg.md", "kschg", "7a"), de: D("de/bgb.md", "bgb", "476"), domain: "Konsumentenschutz/E-Commerce", status: "draft" },
  { query: "verbraucher solidarschuldner genannten Gewährleistung Mängel", family: "keyword", at: A("at/kschg.md", "kschg", "25b"), de: D("de/bgb.md", "bgb", "312e"), domain: "Konsumentenschutz/E-Commerce", status: "draft" },
  { query: "geschäftlichen verkehr allgemeinen", family: "keyword", at: A("at/kschg.md", "kschg", "28"), de: D("de/bgb.md", "bgb", "307"), domain: "Konsumentenschutz/E-Commerce", status: "draft" },
  { query: "bundesgesetz regelt rechtlichen", family: "keyword", at: A("at/ecg.md", "ecg", "1"), de: D("de/bgb.md", "bgb", "166"), domain: "Konsumentenschutz/E-Commerce", status: "draft" },
  { query: "diensteanbieter nutzer angemessene Vertrag", family: "keyword", at: A("at/ecg.md", "ecg", "10"), de: D("de/bgb.md", "bgb", "1360a"), domain: "Konsumentenschutz/E-Commerce", status: "draft" },
  { query: "gericht verwaltungsbehörde rahmen Zuständigkeit Gericht", family: "keyword", at: A("at/ecg.md", "ecg", "22"), de: D("de/bgb.md", "bgb", "71"), domain: "Konsumentenschutz/E-Commerce", status: "draft" },
  { query: "Datenschutz verfassungsbestimmung grundrecht datenschutz", family: "concept", at: A("at/dsg-at.md", "dsg", "1"), de: D("de/bdsg.md", "bdsg", "8"), domain: "Konsumentenschutz/E-Commerce", status: "draft" },
  { query: "artikel anzuwenden sind", family: "keyword", at: A("at/dsg-at.md", "dsg", "2"), de: D("de/bdsg.md", "bdsg", "2"), domain: "Konsumentenschutz/E-Commerce", status: "draft" },
  { query: "artikel inkrafttretensdatum außerkrafttretensdatum Datenschutz", family: "keyword", at: A("at/dsg-at.md", "dsg", "2"), de: D("de/bdsg.md", "bdsg", "36"), domain: "Konsumentenschutz/E-Commerce", status: "draft" },

];

/** Draft entries with reviewed_by + reviewed_at, ready for promotion to corpus.ts. */
export const LEGAL_AT_REVIEWED: DraftEntry[] = LEGAL_AT_PENDING.filter(
  (e) => e.status === "reviewed" && e.reviewed_by && e.reviewed_at
);
