/**
 * Forensic Case A Ground-Truth Katalog for the legacy OCR regression suite.
 * This fixture does not prove raw-document ingestion.
 * Struktur abgeleitet aus handgemachten Analysen (ARCHIV_Analysen + FMA Forderungsunterlagen).
 * Alle Personen, Firmen, Kanzleien und Aktenzeichen sind FIKTIVE Platzhalter.
 * Stand: 23.06.2026
 *
 * Dieser Katalog dient als Abgleich-Basis für Pipeline-Ergebnisse.
 * Jeder Wert wurde aus den manuellen Analysen verifiziert.
 */

export const groundTruth = {
  case_identifier: {
    case_slug: "legal/cases/forensic-case-a-beispiel-alpha",
    case_title: "Forensic Case A — Beispiel/Alpha Apotheken-Betrug",
    jurisdiction: "at",
    verfahrenstyp: "straf",
    aktenzeichen: ["099 099 HV 900/24 y"],
    linked_aktenzeichen: [
      "99 St 901/22 v",
      "99 St 902/25s",
      "99 St 903/22f",
      "999 St 904/22",
      "9 NSt 905/25t",
      "9 C 90S/24p",
      "PAD/24/00000000",
      "99 St 907/242",
      "99 St 907/24w",
      "999 St 908/25i",
    ],
  },

  entities: {
    clients: [
      { name: "Max Beispiel", role: "Beschuldigter -> Anzeiger" },
      { name: "Mag. Erik Muster", role: "Opfer / Apotheker" },
      { name: "Emil Exempel", role: "Opfer / Logistik-GF -> Anzeiger" },
    ],
    opponents: [
      { name: "Anton Platzhalter", role: "Täter", aliases: ["Rudi Tarnname", "Rudy Tarnname"] },
      { name: "Beispiel Labor GmbH", role: "Gegner-Unternehmen" },
      { name: "Alpha Apotheke", role: "Gegner-Apotheke" },
      { name: "Bund / Republik Österreich", role: "Amtshaftungsgegner" },
      { name: "ÖGK", role: "Gegner (DSGVO/Retaxierung)" },
      { name: "Apothekerkammer", role: "Gegner (DSGVO/Datenweitergabe)" },
    ],
    other_persons: [
      { name: "Mag. pharm. Konrad Probe", role: "Mitbeschuldigter / Apotheker" },
      { name: "Greta Maria Fiktiva", role: "Strohfrau (Slowenien)" },
      { name: "Jana Fiktivic", role: "Strohfrau (Kroatien, gesucht)" },
      { name: "Mag. Lukas Advokat", role: "Anwalt Exempel + Probe" },
      { name: "Mag. Anwaltner", role: "Anwalt Muster" },
      { name: "Kanzlei Nord & Süd", role: "Anwalt Platzhalter" },
      { name: "Kanzlei West", role: "Anwalt Muster (zeitweise)" },
      { name: "Samo Primer", role: "Slowenischer Anwalt Platzhalter" },
      { name: "Mag. Sabine Staatsmann", role: "Staatsanwältin (durchgehend)" },
      { name: "Dr. Paul Pruefer", role: "Staatsanwalt (Dez 2023-Feb 2026)" },
      { name: "Clara Probst", role: "Staatsanwältin (März 2025)" },
      { name: "Dr. Ines Verwalter", role: "Insolvenzverwalter Beta Apotheke" },
    ],
  },

  on_numbers: {
    expected_in_ocr: [
      "ON 1.6",
      "ON 10",
      "ON 11",
      "ON 11.2.1",
      "ON 15",
      "ON 19",
      "ON 23",
      "ON 23.18",
      "ON 24",
      "ON 25",
      "ON 27",
      "ON 27.2",
      "ON 272",
      "ON 3",
      "ON 37",
      "ON 4",
      "ON 57",
      "ON 57.2",
      "ON 6.3",
      "ON 74",
      "ON 87",
      "ON 88",
      "ON 2",
      "ON 63",
    ],
    expected_in_html: [
      "ON 1",
      "ON 1.1",
      "ON 1.15",
      "ON 1.17",
      "ON 1.18",
      "ON 1.20",
      "ON 1.34",
      "ON 1.35",
      "ON 1.36",
      "ON 11.2.1",
      "ON 11.2.2",
      "ON 15.7",
      "ON 15.8",
      "ON 16",
      "ON 16.2",
      "ON 19.2",
      "ON 2",
      "ON 25.1",
      "ON 25.2",
      "ON 25.3",
      "ON 25.4",
      "ON 26.2",
      "ON 26.3",
      "ON 30.2",
      "ON 30.3",
      "ON 34.2",
      "ON 35",
      "ON 35.1",
      "ON 35.2",
      "ON 36",
      "ON 40.2.1",
      "ON 40.2.2",
      "ON 40.2.3",
      "ON 40.2.5",
      "ON 40.2.6",
      "ON 40.2.7",
      "ON 40.2.8",
      "ON 40.4.4",
      "ON 40.4.8",
      "ON 40.4.9",
      "ON 40.6.2",
      "ON 40.7.3",
      "ON 40.7.4",
      "ON 42.1",
      "ON 43.1",
      "ON 44.2",
      "ON 47",
      "ON 48.2",
      "ON 49.3",
      "ON 5.2",
      "ON 51.3",
      "ON 54",
      "ON 54.1",
      "ON 55",
      "ON 56",
      "ON 56.1",
      "ON 9.11",
      "ON 9.19",
      "ON 9.4",
      "ON 9.6",
    ],
    key_on_refs: {
      "ON 1.17": { desc: "Einstellung 99 St 901/22 v", date: "2023-11-02" },
      "ON 1.34": { desc: "STA-Urgenz Stellungnahme", date: "2026-02-08" },
      "ON 1.36": { desc: "STA-Urgenz 3x", date: "2026-04-07" },
      "ON 9.4": { desc: "BMSGPK-Weisung (Hoheitlichkeit)" },
      "ON 16.2": { desc: "Finanzprokuratur PA-Anschluss", date: "2022-08-25" },
      "ON 25.1": { desc: "Datenweitergabe ÖGK->Kammer" },
      "ON 26.3": { desc: "Gesamtvertrag ÖGK-Apothekerschaft" },
      "ON 30.3": { desc: "Rechnungshofbericht widerlegt ÖGK" },
      "ON 34.2": { desc: "Finanzprokuratur Anfechtung", date: "2023-11-06" },
      "ON 40.2.3": { desc: "Muster: Provision 700k, Retaxierung 1.5M" },
      "ON 40.2.6": { desc: "Exempel: Strafanzeige + Sicherstellung 900.200" },
      "ON 40.2.8": { desc: "Muster erweitert: Rechnungen, Advokat-Konflikt" },
      "ON 40.4.4": { desc: "Primer: Drohungen 'Unterwelt'" },
      "ON 44.2": { desc: "Einstellung WKStA 99 St 903/22f", date: "2025-06-30" },
      "ON 54": { desc: "Kanzlei Nord Stellungnahme zugesagt", date: "2025-12-18" },
      "ON 56.1": { desc: "Advokat Akteneinsicht (letzter Eintrag)", date: "2026-05-27" },
    },
  },

  fristen: [
    {
      anspruch: "DSGVO Datenweitergabe",
      gegner: "ÖGK",
      kenntnis: "2023-08-02",
      ablauf: "2026-08-02",
      norm: "§ 1489 ABGB",
      status: "CRITICAL",
    },
    {
      anspruch: "DSGVO Datenweitergabe",
      gegner: "Apothekerkammer",
      kenntnis: "2023-08-02",
      ablauf: "~2026-08",
      norm: "§ 1489 ABGB",
      status: "CRITICAL",
    },
    {
      anspruch: "DSGVO über AHG",
      gegner: "Bund",
      kenntnis: "2023-11-02",
      ablauf: "2026-11-02",
      norm: "§ 6 Abs 1 AHG",
      status: "WARNING",
    },
    {
      anspruch: "Retaxierung rechtswidrig",
      gegner: "Bund/ÖGK",
      kenntnis: "2023-11-02",
      ablauf: "2026-11-02",
      norm: "§ 6 AHG",
      status: "WARNING",
    },
    {
      anspruch: "Apothekenverlust",
      gegner: "Bund/ÖGK",
      kenntnis: "2025",
      ablauf: "2028+",
      norm: "§ 6 AHG",
      status: "OK",
    },
    {
      anspruch: "Sicherstellungsunterlassung",
      gegner: "Bund",
      kenntnis: "2024/2025",
      ablauf: "2027/2028",
      norm: "§ 6 AHG",
      status: "OK",
    },
    {
      anspruch: "Verfahrensverzögerung",
      gegner: "Bund",
      kenntnis: "Dauerzustand",
      ablauf: "laufend",
      norm: "Art 6 EMRK",
      status: "OK",
    },
    {
      anspruch: "Disziplinär ÖGK",
      gegner: "BMSGPK",
      kenntnis: "2021",
      ablauf: "VERJÄHRT",
      norm: "BDG § 94",
      status: "VERJAERT",
    },
    {
      anspruch: "Straf gg. Platzhalter",
      gegner: "StA",
      kenntnis: "2021-2024",
      ablauf: "~2031-2034",
      norm: "§ 57 StGB",
      status: "OK",
    },
    {
      anspruch: "§ 195 Fortführung",
      gegner: "LG Wien",
      kenntnis: "2023-11-02",
      ablauf: "TOT",
      norm: "§ 195 StPO",
      status: "VERJAERT",
    },
  ],

  ansprueche_pro_gegner: [
    {
      gegner: "Bund (Finanzprokuratur)",
      ansprueche: [
        {
          position: "DSGVO-Datenweitergabe",
          norm: "§ 1 AHG, Art 9 DSGVO",
          on_beweis: ["ON 2", "ON 25.1", "ON 9.4"],
        },
        {
          position: "Retaxierung rechtswidrig",
          betrag: 1500000,
          norm: "§ 1 AHG",
          on_beweis: ["ON 40.2.3", "ON 26.3"],
        },
        { position: "Apothekenverlust", betrag: 7000000, norm: "§ 1 AHG" },
        { position: "Sicherstellungsunterlassung", betrag: 944200, norm: "§ 110 StPO iVm § 1 AHG" },
        { position: "Verfahrensverzögerung", norm: "Art 6 EMRK" },
      ],
    },
    {
      gegner: "ÖGK",
      ansprueche: [
        { position: "DSGVO-Datenweitergabe", norm: "Art 82 DSGVO" },
        { position: "Retaxierung (Zivil)", betrag: 1500000, norm: "Bereicherungsrecht" },
      ],
    },
    {
      gegner: "Apothekerkammer",
      ansprueche: [{ position: "Illegal beschaffte Daten", norm: "Art 82 DSGVO" }],
    },
    {
      gegner: "Platzhalter",
      ansprueche: [
        { position: "Veruntreuung Gamma Logistik", betrag: 944200, norm: "§§ 146, 147 StGB" },
        { position: "Firmenwert Gamma Logistik", betrag: 10000000 },
        { position: "Delta Logistik", betrag: 400000 },
        { position: "Exempel persönlich", betrag: 400000 },
        { position: "Provision Muster", betrag: 700000 },
        { position: "Weitere Rechnungen Muster", betrag: 626449.2 },
      ],
    },
  ],

  schadenstabelle: {
    muster: {
      provision_platzhalter: 700000,
      weitere_rechnungen: 626449.2,
      retaxierung_oegk: 1500000,
      apothekenverlust: 7000000,
      disziplinarstrafe: 40000,
      konkurs_omega: 35000,
      sanierungskosten_min: 50000,
      gesamt_konservativ: 9996549.2,
      gesamt_inkl_immateriell: 10100000,
    },
    exempel: {
      veruntreuung_gamma_logistik: 944200,
      firmenwert_gamma_logistik: 10000000,
      delta_logistik: 400000,
      persoenlich_brutto: 1100000,
      persoenlich_bereinigt: 536987.51,
      sozialabgaben: 120000,
      insolvenzvermeidung: 100000,
      klage_nemo: 61987.51,
      vorenthaltene_gehaelter: 175000,
      vorenthaltene_abfindung: 200000,
      privatbeteiligtenanschluss_gesamt: 11744200,
    },
  },

  schriftsatztypen: [
    { type: "strafantrag", adressat: "STA Wien", norm: "§ 28 StPO", paket: "A" },
    { type: "amtshaftungsklage", adressat: "Finanzprokuratur/LG ZRS", norm: "§ 1 AHG", paket: "B" },
    { type: "privatbeteiligtenanspruch", adressat: "Gericht", norm: "§ 67 StPO", paket: "A" },
    { type: "sicherstellungsantrag", adressat: "STA", norm: "§ 110 StPO", paket: "A" },
    { type: "dsgvo_beschwerde", adressat: "ÖGK+Kammer", norm: "Art 82 DSGVO", paket: "E" },
    { type: "dsgvo_beschwerde_dsb", adressat: "DSB", norm: "Art 77 DSGVO", paket: "F.1" },
    { type: "finanzstrafanzeige", adressat: "Finanzstrafbehörde", paket: "F.2" },
    { type: "disziplinarantrag_sta", adressat: "DiszKomm BMJ", paket: "C.1" },
    { type: "disziplinarantrag_polizei", adressat: "DiszKomm BMI", paket: "C.2" },
    { type: "aufsichtsbeschwerde_oegk", adressat: "BMSGPK", paket: "C.3" },
    { type: "verzoegerungsruege", adressat: "Gericht/StA", norm: "Art 6 EMRK", paket: "C.5" },
    { type: "fortfuehrungsantrag_193", adressat: "StA", norm: "§ 193 Abs 2 StPO", paket: "D" },
    { type: "offenlegung_finanzamt", adressat: "Finanzamt", paket: "F.3" },
    { type: "sanierungsplan_anforderung", adressat: "HG Wien/Dr. Verwalter", paket: "Beweis" },
    { type: "volksanwaltschaft_beschwerde", adressat: "Volksanwaltschaft", paket: "optional" },
    { type: "urgenz_bestaende", adressat: "SOLBE/BASG/etc", paket: "Beweis" },
  ],

  widersprueche: [
    {
      id: "W1",
      desc: "Sicherstellungs-Datum: 03.06.2026 vs 28.05.2024",
      severity: "high",
      correct: "2024-05-28",
      wrong: "2026-06-03",
    },
    {
      id: "W2",
      desc: "Exempel: 1.168.000 vs 1.096.000 vs 1.100.000",
      severity: "medium",
      correct: 1100000,
      wrong: [1168000, 1096000],
    },
    {
      id: "W3",
      desc: "Sicherungsbetrag: 600.000 vs 900.200",
      severity: "high",
      correct: 900200,
      wrong: 600000,
    },
    { id: "W4", desc: "Muster-Gesamtschaden schwankend", severity: "medium" },
    { id: "W5", desc: "Stillstand 07.04.2026 vs Aktivität 27.05.2026", severity: "low" },
  ],

  doppelzaehlungen: [
    { desc: "GF-Honorar 210.000 = GF-Vergütung 175.000", severity: "medium" },
    { desc: "Bürgschaft Nemo 69.000 ≈ Nemo-Klage 61.987,51", severity: "medium" },
  ],

  forensische_befunde: {
    zentrale_these: "Asymmetrie: Staat verfolgt Opfer, Täter unbehelligt",
    asymmetrie_indizien: [
      "Keine Vernehmung Platzhalter in 4+ Jahren",
      "Keine Kontosperre (Täterkonten NIE gesperrt)",
      "Keine Sicherstellung (Antrag 900.200 ignoriert)",
      "Keine Durchsuchung, Festnahme, Rechtshilfe",
      "Opferkonten via Retaxierung eingefroren",
      "Polizei hielt Täter für 'Datenschutzbeauftragten'",
    ],
    verfahrensverstoesse_gegenseite: 5,
    keine_klage: true,
    exempel_rollenwechsel: "Beschuldigter -> Anzeiger",
    advokat_konflikt: "Vertritt Exempel + Probe (Mitbeschuldigte)",
  },

  normen: [
    "§ 1 AHG",
    "§ 6 Abs 1 AHG",
    "§ 8 AHG",
    "§ 9 AHG",
    "§ 1489 ABGB",
    "§ 1497 ABGB",
    "§ 146 StGB",
    "§ 147 StGB",
    "§ 148 StGB",
    "§ 57 StGB",
    "§ 107 StGB",
    "§ 28 StPO",
    "§ 110 StPO",
    "§ 112 StPO",
    "§ 164 StPO",
    "§ 193 Abs 2 StPO",
    "§ 195 StPO",
    "§ 100 Abs 2 Z 3 StPO",
    "§ 67 StPO",
    "Art 9 DSGVO",
    "Art 82 DSGVO",
    "Art 77 DSGVO",
    "Art 6 EMRK",
  ],

  institutionen: [
    "Finanzprokuratur",
    "STA Wien",
    "LG ZRS Wien",
    "DiszKomm BMJ",
    "DiszKomm BMI",
    "DiszKomm BMSGPK",
    "DSB",
    "Finanzstrafbehörde",
    "Finanzamt",
    "HG Wien/Dr. Verwalter",
    "Volksanwaltschaft",
    "ÖGK+Apothekerkammer",
    "SOLBE/BASG/Maribor/HSI",
  ],

  gz_validation: {
    hauptakt: "099 099 HV 900/24 y",
    verfahren: [
      {
        gz: "99 St 901/22 v",
        status: "eingestellt 2023-11-02",
        beschuldigte: ["Probe", "Muster", "Exempel"],
      },
      { gz: "99 St 902/25s", status: "offen", gegen: "Platzhalter" },
      { gz: "99 St 903/22f", status: "eingestellt 2025-06-30", gegenstand: "Epsilon Bau s.r.o." },
      { gz: "999 St 904/22", status: "Übertragung" },
      { gz: "9 NSt 905/25t", status: "offen", gegen: "Platzhalter" },
      { gz: "9 C 90S/24p", status: "Zivilverfahren" },
      { gz: "099 099 S 00909/25p", status: "Insolvenz Beta Apotheke" },
    ],
  },

  pipeline_erwartungswerte: {
    layer_0: { doc_types_min: 5, jurisdiction: "at" },
    layer_1: { on_count_min: 20, hallucination_gate: true },
    layer_2: { entities_min: 12, aliases_expected: true, roles_expected: true },
    layer_3: { findings_min: 7, verfahrensverstoesse_gegenseite_min: 5 },
    layer_4: { norms_min: 10, corpus_volltext_required: ["§ 6 AHG", "§ 1489 ABGB"] },
    layer_5: {
      muster_total_min: 9990000,
      muster_total_max: 10100000,
      exempel_pa: 11744200,
      overlap_warnings_min: 2,
      positions_min: 15,
    },
    layer_5b: { critical_fristen_min: 2, verjaerte_min: 2 },
    layer_5l: { gegner_dimension_required: true, ansprueche_pro_gegner_min: 4 },
    layer_6: { draft_types_min: 6, legacy_count: 6, expected_total: 16 },
    layer_7: { min_score: 75, contradiction_findings_min: 3 },
    post_pipeline: { contradiction_queries_min: 3 },
  },
} as const;

export type GroundTruth = typeof groundTruth;
