/**
 * Toni Gericht Ground-Truth Katalog for the legacy OCR regression suite.
 * This fixture does not prove raw-document ingestion.
 * Extrahiert aus handgemachten Analysen (ARCHIV_Analysen + FMA Forderungsunterlagen)
 * Stand: 23.06.2026
 *
 * Dieser Katalog dient als Abgleich-Basis für Pipeline-Ergebnisse.
 * Jeder Wert wurde aus den manuellen Analysen verifiziert.
 */

export const groundTruth = {
  case_identifier: {
    case_slug: "legal/cases/toni-gericht-vasic-doskar",
    case_title: "Toni Gericht — Vasic/Doskar Apotheken-Betrug",
    jurisdiction: "at",
    verfahrenstyp: "straf",
    aktenzeichen: ["046 045 HV 29/24 y"],
    linked_aktenzeichen: [
      "39 St 116/22 v",
      "63 St 85/25s",
      "23 St 4/22f",
      "410 St 131/22",
      "6 NSt 59/25t",
      "6 C 23S/24p",
      "PAD/24/01129234",
      "79 St 123/242",
      "79 St 123/24w",
      "409 St 58/25i",
    ],
  },

  entities: {
    clients: [
      { name: "Marjan Vasic", role: "Beschuldigter -> Anzeiger" },
      { name: "Mag. Rudolf Mather", role: "Opfer / Apotheker" },
      { name: "Martin Eckerstorfer", role: "Opfer / Logistik-GF -> Anzeiger" },
    ],
    opponents: [
      { name: "Adis Hrustemovic", role: "Täter", aliases: ["Toni Remik", "Tony Remik"] },
      { name: "Lifebrain GmbH", role: "Gegner-Unternehmen" },
      { name: "Doskar Apotheke", role: "Gegner-Apotheke" },
      { name: "Bund / Republik Österreich", role: "Amtshaftungsgegner" },
      { name: "ÖGK", role: "Gegner (DSGVO/Retaxierung)" },
      { name: "Apothekerkammer", role: "Gegner (DSGVO/Datenweitergabe)" },
    ],
    other_persons: [
      { name: "Mag. pharm. Michael Kuhn", role: "Mitbeschuldigter / Apotheker" },
      { name: "Gabriela Maria Bumbac", role: "Strohfrau (Slowenien)" },
      { name: "Jasminka Prlog", role: "Strohfrau (Kroatien, gesucht)" },
      { name: "Mag. Ralph Kilches", role: "Anwalt Eckerstorfer + Kuhn" },
      { name: "Mag. Schönknecht", role: "Anwalt Mather" },
      { name: "Rast & Musliu", role: "Anwalt Hrustemovic" },
      { name: "Wolf Theiss", role: "Anwalt Mather (zeitweise)" },
      { name: "Simon Dolinsek", role: "Slowenischer Anwalt Hrustemovic" },
      { name: "Mag. Katharina Schmid-Siegel", role: "Staatsanwältin (durchgehend)" },
      { name: "Dr. Michael Schietz", role: "Staatsanwalt (Dez 2023-Feb 2026)" },
      { name: "Claudia Pöttinger", role: "Staatsanwältin (März 2025)" },
      { name: "Dr. Erwin Senoner", role: "Insolvenzverwalter Stern Apotheke" },
    ],
  },

  on_numbers: {
    expected_in_ocr: [
      "ON 1.6",
      "ON 10",
      "ON 11",
      "ON 11.2.1",
      "ON 15",
      "ON 19",
      "ON 23",
      "ON 23.18",
      "ON 24",
      "ON 25",
      "ON 27",
      "ON 27.2",
      "ON 272",
      "ON 3",
      "ON 37",
      "ON 4",
      "ON 57",
      "ON 57.2",
      "ON 6.3",
      "ON 74",
      "ON 87",
      "ON 88",
      "ON 2",
      "ON 63",
    ],
    expected_in_html: [
      "ON 1",
      "ON 1.1",
      "ON 1.15",
      "ON 1.17",
      "ON 1.18",
      "ON 1.20",
      "ON 1.34",
      "ON 1.35",
      "ON 1.36",
      "ON 11.2.1",
      "ON 11.2.2",
      "ON 15.7",
      "ON 15.8",
      "ON 16",
      "ON 16.2",
      "ON 19.2",
      "ON 2",
      "ON 25.1",
      "ON 25.2",
      "ON 25.3",
      "ON 25.4",
      "ON 26.2",
      "ON 26.3",
      "ON 30.2",
      "ON 30.3",
      "ON 34.2",
      "ON 35",
      "ON 35.1",
      "ON 35.2",
      "ON 36",
      "ON 40.2.1",
      "ON 40.2.2",
      "ON 40.2.3",
      "ON 40.2.5",
      "ON 40.2.6",
      "ON 40.2.7",
      "ON 40.2.8",
      "ON 40.4.4",
      "ON 40.4.8",
      "ON 40.4.9",
      "ON 40.6.2",
      "ON 40.7.3",
      "ON 40.7.4",
      "ON 42.1",
      "ON 43.1",
      "ON 44.2",
      "ON 47",
      "ON 48.2",
      "ON 49.3",
      "ON 5.2",
      "ON 51.3",
      "ON 54",
      "ON 54.1",
      "ON 55",
      "ON 56",
      "ON 56.1",
      "ON 9.11",
      "ON 9.19",
      "ON 9.4",
      "ON 9.6",
    ],
    key_on_refs: {
      "ON 1.17": { desc: "Einstellung 39 St 116/22 v", date: "2023-11-02" },
      "ON 1.34": { desc: "STA-Urgenz Stellungnahme", date: "2026-02-08" },
      "ON 1.36": { desc: "STA-Urgenz 3x", date: "2026-04-07" },
      "ON 9.4": { desc: "BMSGPK-Weisung (Hoheitlichkeit)" },
      "ON 16.2": { desc: "Finanzprokuratur PA-Anschluss", date: "2022-08-25" },
      "ON 25.1": { desc: "Datenweitergabe ÖGK->Kammer" },
      "ON 26.3": { desc: "Gesamtvertrag ÖGK-Apothekerschaft" },
      "ON 30.3": { desc: "Rechnungshofbericht widerlegt ÖGK" },
      "ON 34.2": { desc: "Finanzprokuratur Anfechtung", date: "2023-11-06" },
      "ON 40.2.3": { desc: "Mather: Provision 700k, Retaxierung 1.5M" },
      "ON 40.2.6": { desc: "Eckerstorfer: Strafanzeige + Sicherstellung 900.200" },
      "ON 40.2.8": { desc: "Mather erweitert: Rechnungen, Kilches-Konflikt" },
      "ON 40.4.4": { desc: "Dolinsek: Drohungen 'Unterwelt'" },
      "ON 44.2": { desc: "Einstellung WKStA 23 St 4/22f", date: "2025-06-30" },
      "ON 54": { desc: "Rast Stellungnahme zugesagt", date: "2025-12-18" },
      "ON 56.1": { desc: "Kilches Akteneinsicht (letzter Eintrag)", date: "2026-05-27" },
    },
  },

  fristen: [
    {
      anspruch: "DSGVO Datenweitergabe",
      gegner: "ÖGK",
      kenntnis: "2023-08-02",
      ablauf: "2026-08-02",
      norm: "§ 1489 ABGB",
      status: "CRITICAL",
    },
    {
      anspruch: "DSGVO Datenweitergabe",
      gegner: "Apothekerkammer",
      kenntnis: "2023-08-02",
      ablauf: "~2026-08",
      norm: "§ 1489 ABGB",
      status: "CRITICAL",
    },
    {
      anspruch: "DSGVO über AHG",
      gegner: "Bund",
      kenntnis: "2023-11-02",
      ablauf: "2026-11-02",
      norm: "§ 6 Abs 1 AHG",
      status: "WARNING",
    },
    {
      anspruch: "Retaxierung rechtswidrig",
      gegner: "Bund/ÖGK",
      kenntnis: "2023-11-02",
      ablauf: "2026-11-02",
      norm: "§ 6 AHG",
      status: "WARNING",
    },
    {
      anspruch: "Apothekenverlust",
      gegner: "Bund/ÖGK",
      kenntnis: "2025",
      ablauf: "2028+",
      norm: "§ 6 AHG",
      status: "OK",
    },
    {
      anspruch: "Sicherstellungsunterlassung",
      gegner: "Bund",
      kenntnis: "2024/2025",
      ablauf: "2027/2028",
      norm: "§ 6 AHG",
      status: "OK",
    },
    {
      anspruch: "Verfahrensverzögerung",
      gegner: "Bund",
      kenntnis: "Dauerzustand",
      ablauf: "laufend",
      norm: "Art 6 EMRK",
      status: "OK",
    },
    {
      anspruch: "Disziplinär ÖGK",
      gegner: "BMSGPK",
      kenntnis: "2021",
      ablauf: "VERJÄHRT",
      norm: "BDG § 94",
      status: "VERJAERT",
    },
    {
      anspruch: "Straf gg. Hrustemovic",
      gegner: "StA",
      kenntnis: "2021-2024",
      ablauf: "~2031-2034",
      norm: "§ 57 StGB",
      status: "OK",
    },
    {
      anspruch: "§ 195 Fortführung",
      gegner: "LG Wien",
      kenntnis: "2023-11-02",
      ablauf: "TOT",
      norm: "§ 195 StPO",
      status: "VERJAERT",
    },
  ],

  ansprueche_pro_gegner: [
    {
      gegner: "Bund (Finanzprokuratur)",
      ansprueche: [
        {
          position: "DSGVO-Datenweitergabe",
          norm: "§ 1 AHG, Art 9 DSGVO",
          on_beweis: ["ON 2", "ON 25.1", "ON 9.4"],
        },
        {
          position: "Retaxierung rechtswidrig",
          betrag: 1500000,
          norm: "§ 1 AHG",
          on_beweis: ["ON 40.2.3", "ON 26.3"],
        },
        { position: "Apothekenverlust", betrag: 7000000, norm: "§ 1 AHG" },
        { position: "Sicherstellungsunterlassung", betrag: 944200, norm: "§ 110 StPO iVm § 1 AHG" },
        { position: "Verfahrensverzögerung", norm: "Art 6 EMRK" },
      ],
    },
    {
      gegner: "ÖGK",
      ansprueche: [
        { position: "DSGVO-Datenweitergabe", norm: "Art 82 DSGVO" },
        { position: "Retaxierung (Zivil)", betrag: 1500000, norm: "Bereicherungsrecht" },
      ],
    },
    {
      gegner: "Apothekerkammer",
      ansprueche: [{ position: "Illegal beschaffte Daten", norm: "Art 82 DSGVO" }],
    },
    {
      gegner: "Hrustemovic",
      ansprueche: [
        { position: "Veruntreuung Cutting Edge", betrag: 944200, norm: "§§ 146, 147 StGB" },
        { position: "Firmenwert Cutting Edge", betrag: 10000000 },
        { position: "Logcon East", betrag: 400000 },
        { position: "Eckerstorfer persönlich", betrag: 400000 },
        { position: "Provision Mather", betrag: 700000 },
        { position: "Weitere Rechnungen Mather", betrag: 626449.2 },
      ],
    },
  ],

  schadenstabelle: {
    mather: {
      provision_hrustemovic: 700000,
      weitere_rechnungen: 626449.2,
      retaxierung_oegk: 1500000,
      apothekenverlust: 7000000,
      disziplinarstrafe: 40000,
      konkurs_macor: 35000,
      sanierungskosten_min: 50000,
      gesamt_konservativ: 9996549.2,
      gesamt_inkl_immateriell: 10100000,
    },
    eckerstorfer: {
      veruntreuung_cutting_edge: 944200,
      firmenwert_cutting_edge: 10000000,
      logcon_east: 400000,
      persoenlich_brutto: 1100000,
      persoenlich_bereinigt: 536987.51,
      sozialabgaben: 120000,
      insolvenzvermeidung: 100000,
      klage_nunner: 61987.51,
      vorenthaltene_gehaelter: 175000,
      vorenthaltene_abfindung: 200000,
      privatbeteiligtenanschluss_gesamt: 11744200,
    },
  },

  schriftsatztypen: [
    { type: "strafantrag", adressat: "STA Wien", norm: "§ 28 StPO", paket: "A" },
    { type: "amtshaftungsklage", adressat: "Finanzprokuratur/LG ZRS", norm: "§ 1 AHG", paket: "B" },
    { type: "privatbeteiligtenanspruch", adressat: "Gericht", norm: "§ 67 StPO", paket: "A" },
    { type: "sicherstellungsantrag", adressat: "STA", norm: "§ 110 StPO", paket: "A" },
    { type: "dsgvo_beschwerde", adressat: "ÖGK+Kammer", norm: "Art 82 DSGVO", paket: "E" },
    { type: "dsgvo_beschwerde_dsb", adressat: "DSB", norm: "Art 77 DSGVO", paket: "F.1" },
    { type: "finanzstrafanzeige", adressat: "Finanzstrafbehörde", paket: "F.2" },
    { type: "disziplinarantrag_sta", adressat: "DiszKomm BMJ", paket: "C.1" },
    { type: "disziplinarantrag_polizei", adressat: "DiszKomm BMI", paket: "C.2" },
    { type: "aufsichtsbeschwerde_oegk", adressat: "BMSGPK", paket: "C.3" },
    { type: "verzoegerungsruege", adressat: "Gericht/StA", norm: "Art 6 EMRK", paket: "C.5" },
    { type: "fortfuehrungsantrag_193", adressat: "StA", norm: "§ 193 Abs 2 StPO", paket: "D" },
    { type: "offenlegung_finanzamt", adressat: "Finanzamt", paket: "F.3" },
    { type: "sanierungsplan_anforderung", adressat: "HG Wien/Dr. Senoner", paket: "Beweis" },
    { type: "volksanwaltschaft_beschwerde", adressat: "Volksanwaltschaft", paket: "optional" },
    { type: "urgenz_bestaende", adressat: "SOLBE/BASG/etc", paket: "Beweis" },
  ],

  widersprueche: [
    {
      id: "W1",
      desc: "Sicherstellungs-Datum: 03.06.2026 vs 28.05.2024",
      severity: "high",
      correct: "2024-05-28",
      wrong: "2026-06-03",
    },
    {
      id: "W2",
      desc: "Eckerstorfer: 1.168.000 vs 1.096.000 vs 1.100.000",
      severity: "medium",
      correct: 1100000,
      wrong: [1168000, 1096000],
    },
    {
      id: "W3",
      desc: "Sicherungsbetrag: 600.000 vs 900.200",
      severity: "high",
      correct: 900200,
      wrong: 600000,
    },
    { id: "W4", desc: "Mather-Gesamtschaden schwankend", severity: "medium" },
    { id: "W5", desc: "Stillstand 07.04.2026 vs Aktivität 27.05.2026", severity: "low" },
  ],

  doppelzaehlungen: [
    { desc: "GF-Honorar 210.000 = GF-Vergütung 175.000", severity: "medium" },
    { desc: "Bürgschaft Nunner 69.000 ≈ Nunner-Klage 61.987,51", severity: "medium" },
  ],

  forensische_befunde: {
    zentrale_these: "Asymmetrie: Staat verfolgt Opfer, Täter unbehelligt",
    asymmetrie_indizien: [
      "Keine Vernehmung Hrustemovic in 4+ Jahren",
      "Keine Kontosperre (Täterkonten NIE gesperrt)",
      "Keine Sicherstellung (Antrag 900.200 ignoriert)",
      "Keine Durchsuchung, Festnahme, Rechtshilfe",
      "Opferkonten via Retaxierung eingefroren",
      "Polizei hielt Täter für 'Datenschutzbeauftragten'",
    ],
    verfahrensverstoesse_gegenseite: 5,
    keine_klage: true,
    eckerstorfer_rollenwechsel: "Beschuldigter -> Anzeiger",
    kilches_konflikt: "Vertritt Eckerstorfer + Kuhn (Mitbeschuldigte)",
  },

  normen: [
    "§ 1 AHG",
    "§ 6 Abs 1 AHG",
    "§ 8 AHG",
    "§ 9 AHG",
    "§ 1489 ABGB",
    "§ 1497 ABGB",
    "§ 146 StGB",
    "§ 147 StGB",
    "§ 148 StGB",
    "§ 57 StGB",
    "§ 107 StGB",
    "§ 28 StPO",
    "§ 110 StPO",
    "§ 112 StPO",
    "§ 164 StPO",
    "§ 193 Abs 2 StPO",
    "§ 195 StPO",
    "§ 100 Abs 2 Z 3 StPO",
    "§ 67 StPO",
    "Art 9 DSGVO",
    "Art 82 DSGVO",
    "Art 77 DSGVO",
    "Art 6 EMRK",
  ],

  institutionen: [
    "Finanzprokuratur",
    "STA Wien",
    "LG ZRS Wien",
    "DiszKomm BMJ",
    "DiszKomm BMI",
    "DiszKomm BMSGPK",
    "DSB",
    "Finanzstrafbehörde",
    "Finanzamt",
    "HG Wien/Dr. Senoner",
    "Volksanwaltschaft",
    "ÖGK+Apothekerkammer",
    "SOLBE/BASG/Maribor/HSI",
  ],

  gz_validation: {
    hauptakt: "046 045 HV 29/24 y",
    verfahren: [
      {
        gz: "39 St 116/22 v",
        status: "eingestellt 2023-11-02",
        beschuldigte: ["Kuhn", "Mather", "Eckerstorfer"],
      },
      { gz: "63 St 85/25s", status: "offen", gegen: "Hrustemovic" },
      { gz: "23 St 4/22f", status: "eingestellt 2025-06-30", gegenstand: "Sparta Bau s.r.o." },
      { gz: "410 St 131/22", status: "Übertragung" },
      { gz: "6 NSt 59/25t", status: "offen", gegen: "Hrustemovic" },
      { gz: "6 C 23S/24p", status: "Zivilverfahren" },
      { gz: "007 003 S 00049/25p", status: "Insolvenz Stern Apotheke" },
    ],
  },

  pipeline_erwartungswerte: {
    layer_0: { doc_types_min: 5, jurisdiction: "at" },
    layer_1: { on_count_min: 20, hallucination_gate: true },
    layer_2: { entities_min: 12, aliases_expected: true, roles_expected: true },
    layer_3: { findings_min: 7, verfahrensverstoesse_gegenseite_min: 5 },
    layer_4: { norms_min: 10, corpus_volltext_required: ["§ 6 AHG", "§ 1489 ABGB"] },
    layer_5: {
      mather_total_min: 9990000,
      mather_total_max: 10100000,
      eckerstorfer_pa: 11744200,
      overlap_warnings_min: 2,
      positions_min: 15,
    },
    layer_5b: { critical_fristen_min: 2, verjaerte_min: 2 },
    layer_5l: { gegner_dimension_required: true, ansprueche_pro_gegner_min: 4 },
    layer_6: { draft_types_min: 6, legacy_count: 6, expected_total: 16 },
    layer_7: { min_score: 75, contradiction_findings_min: 3 },
    post_pipeline: { contradiction_queries_min: 3 },
  },
} as const;

export type GroundTruth = typeof groundTruth;
