// @vitest-environment node
import { describe, expect, it, vi } from "vitest";

vi.mock("@/lib/engine", () => ({ ENGINE_URL: "http://engine.test" }));

vi.mock("@/lib/api-handler", () => ({
  createHandler:
    (
      opts: { body?: { parse: (d: unknown) => unknown } },
      handler: (ctx: unknown, body: unknown) => Promise<Response>
    ) =>
    async (req: Request) => {
      const ctx = { brainId: "brain-1", user: { id: "u1", email: "a@b.at" }, headers: {} };
      return handler(ctx, opts.body ? opts.body.parse(await req.json()) : undefined);
    },
}));

vi.mock("@/lib/docx-export", () => ({
  generateDocx: vi.fn(async () => new Uint8Array([1, 2, 3])),
}));

import { POST } from "./route";
import { generateDocx } from "@/lib/docx-export";

function exportDocx(body: Record<string, unknown>) {
  return POST(
    new Request("http://x/api/word-export", {
      method: "POST",
      body: JSON.stringify(body),
    }) as never
  );
}

describe("POST /api/word-export — KI-Kennzeichnung (Art. 50 KI-VO)", () => {
  it("marks exports as AI-generated by default", async () => {
    const res = await exportDocx({ title: "Entwurf", markdown: "Text" });
    expect(res.status).toBe(200);
    expect(vi.mocked(generateDocx).mock.calls.at(-1)?.[1]).toMatchObject({ aiGenerated: true });
  });

  it("leaves template-filled documents unmarked when the caller says so", async () => {
    const res = await exportDocx({ title: "Vollmacht", markdown: "Text", ai_generated: false });
    expect(res.status).toBe(200);
    expect(vi.mocked(generateDocx).mock.calls.at(-1)?.[1]).toMatchObject({ aiGenerated: false });
  });
});
