// Shared icon registry + tone-aware accent tiles for the marketing surface.
// Pure module (no hooks) — safe to import from server components.

import {
  Brain,
  Database,
  GitBranch,
  Search,
  Zap,
  Shield,
  Layers,
  Network,
  Megaphone,
  Gift,
  Handshake,
  CalendarClock,
  Clock,
  Mail,
  ShieldAlert,
  Calculator,
  Landmark,
  FileText,
  FolderOpen,
  MessageSquare,
  Users,
  EyeOff,
  ShieldCheck,
  FileSignature,
  Lock,
  ScanSearch,
  Download,
  User,
  Building2,
  Info,
  Sparkles,
  BarChart3,
  FileClock,
  Gavel,
  PenTool,
  Languages,
  Inbox,
  CheckSquare,
  Check,
  BookOpen,
  AlertTriangle,
  Gauge,
  FileArchive,
  Cpu,
  CreditCard,
  RefreshCw,
  Workflow,
  GitCompare,
  FileSearch,
  Mic,
  Server,
  FileCheck,
  BadgeCheck,
  Briefcase,
  Eye,
  Globe,
  Heart,
  Scale,
  CheckCircle2,
  Target,
  TrendingUp,
  type LucideIcon,
} from "lucide-react";

/** Icon prop accepted by marketing primitives: a Lucide component or an
 *  ICONS registry key (string). Strings keep props serializable across the
 *  RSC boundary so content arrays can stay data-only. */
export type IconProp = LucideIcon | string;

export function resolveIcon(icon: IconProp, fallback: LucideIcon = Layers): LucideIcon {
  return typeof icon === "string" ? (ICONS[icon] ?? fallback) : icon;
}

export const ICONS: Record<string, LucideIcon> = {
  Brain,
  Database,
  GitBranch,
  Search,
  Zap,
  Shield,
  Layers,
  Network,
  Megaphone,
  Gift,
  Handshake,
  CalendarClock,
  Clock,
  Mail,
  ShieldAlert,
  Calculator,
  Landmark,
  FileText,
  FolderOpen,
  MessageSquare,
  Users,
  EyeOff,
  ShieldCheck,
  FileSignature,
  Lock,
  ScanSearch,
  Download,
  User,
  Building2,
  Info,
  Sparkles,
  BarChart3,
  FileClock,
  Gavel,
  PenTool,
  Languages,
  Inbox,
  CheckSquare,
  Check,
  BookOpen,
  AlertTriangle,
  Gauge,
  FileArchive,
  Cpu,
  CreditCard,
  RefreshCw,
  Workflow,
  GitCompare,
  FileSearch,
  Mic,
  Server,
  FileCheck,
  BadgeCheck,
  Briefcase,
  Eye,
  Globe,
  Heart,
  Scale,
  CheckCircle2,
  Target,
  TrendingUp,
};

// Tone-aware accent icon-tiles. On light surfaces the -700/-50/-200 shades
// keep AA contrast; on dark we use the -400 text + alpha fills. accentTile()
// is the single source — replaces the old COLOR_MAP / LIGHT_COLOR_MAP split.
const ACCENT_TILE = {
  light: {
    violet: "brand-text bg-violet-50 border-violet-200",
    blue: "text-blue-700 bg-blue-50 border-blue-200",
    emerald: "text-emerald-700 bg-emerald-50 border-emerald-200",
    amber: "text-amber-700 bg-amber-50 border-amber-200",
    rose: "text-[color:var(--ds-category-rose-text)] bg-[color:var(--ds-category-rose-bg)] border-[color:var(--ds-category-rose-border)]",
    purple: "text-purple-700 bg-purple-50 border-purple-200",
    orange: "text-orange-700 bg-orange-50 border-orange-200",
    gray: "text-[color:var(--ds-neutral-text)] bg-[color:var(--ds-neutral-bg)] border-[color:var(--ds-neutral-border)]",
  },
  slate: {
    violet: "brand-text brand-soft brand-border",
    blue: "text-blue-400 bg-blue-500/10 border-blue-500/20",
    emerald: "text-emerald-400 bg-emerald-500/10 border-emerald-500/20",
    amber: "text-amber-400 bg-amber-500/10 border-amber-500/20",
    rose: "text-[color:var(--ds-category-rose-text)] bg-[color:var(--ds-category-rose-bg)] border-[color:var(--ds-category-rose-border)]",
    purple: "text-purple-400 bg-purple-500/10 border-purple-500/20",
  },
  dark: {
    violet: "brand-text brand-soft brand-border",
    blue: "text-blue-400 bg-blue-500/10 border-blue-500/20",
    emerald: "text-emerald-400 bg-emerald-500/10 border-emerald-500/20",
    amber: "text-amber-400 bg-amber-500/10 border-amber-500/20",
    rose: "text-[color:var(--ds-category-rose-text)] bg-[color:var(--ds-category-rose-bg)] border-[color:var(--ds-category-rose-border)]",
    purple: "text-purple-400 bg-purple-500/10 border-purple-500/20",
  },
  dashboard: {
    violet: "brand-text brand-soft brand-border",
    blue: "text-blue-400 bg-blue-500/10 border-blue-500/20",
    emerald: "text-emerald-400 bg-emerald-500/10 border-emerald-500/20",
    amber: "text-amber-400 bg-amber-500/10 border-amber-500/20",
    rose: "text-[color:var(--ds-category-rose-text)] bg-[color:var(--ds-category-rose-bg)] border-[color:var(--ds-category-rose-border)]",
    purple: "text-purple-400 bg-purple-500/10 border-purple-500/20",
  },
} as const;

export type Tone = "light" | "slate" | "dark" | "dashboard";

export function accentTile(color: string, tone: Tone = "light"): string {
  const map = ACCENT_TILE[tone];
  return map[color as keyof typeof map] ?? map.blue;
}
