import type { Lang } from "@/content/site";

// ─────────────────────────────────────────────────────────────────────────────
// Dashboard bilingual strings — DE (fallback) / EN
// One source of truth for sidebar, topbar, page headers, empty states, errors.
// ─────────────────────────────────────────────────────────────────────────────

export type { Lang };

type BiString = { de: string; en: string };

export const D = {
  // ── Sidebar: section titles ──
  "nav.section.brain": { de: "Gehirn", en: "Brain" },
  "nav.section.cases_deadlines": { de: "Akten & Fristen", en: "Cases & Deadlines" },
  "nav.section.research": { de: "Recherche", en: "Research" },
  "nav.section.drafts_billing": { de: "Schriftsätze & Abrechnung", en: "Drafts & Billing" },
  "nav.section.data_integration": { de: "Daten & Integration", en: "Data & Integration" },
  "nav.section.admin": { de: "Verwaltung", en: "Administration" },
  "nav.section.industries": { de: "Branchen", en: "Industries" },

  // ── Sidebar: nav items (brain) ──
  "nav.overview": { de: "Übersicht", en: "Overview" },
  "nav.assistant": { de: "Assistant", en: "Assistant" },
  "nav.query": { de: "Query", en: "Query" },
  "nav.agents": { de: "Agenten", en: "Agents" },
  "nav.approvals": { de: "Freigaben", en: "Approvals" },
  "nav.brain": { de: "Brain", en: "Brain" },
  "nav.graph": { de: "Graph", en: "Graph" },
  "nav.upload": { de: "Upload", en: "Upload" },
  "nav.rag_eval": { de: "RAG-Eval", en: "RAG Eval" },

  // ── Sidebar: nav items (cases & deadlines) ──
  "nav.cases": { de: "Akten", en: "Cases" },
  "nav.contacts": { de: "Kontakte", en: "Contacts" },
  "nav.contracts": { de: "Verträge", en: "Contracts" },
  "nav.vault": { de: "Dokumenten-Vault", en: "Document Vault" },
  "nav.deadlines": { de: "Fristen", en: "Deadlines" },
  "nav.opponents": { de: "Gegner", en: "Opponents" },
  "nav.client_portal": { de: "Mandanten-Portal", en: "Client Portal" },

  // ── Sidebar: nav items (research) ──
  "nav.legal_research": { de: "Legal Research", en: "Legal Research" },
  "nav.analyze": { de: "Dokument-Analyse", en: "Document Analysis" },
  "nav.precedent_search": { de: "Präzedenzsuche", en: "Precedent Search" },
  "nav.translate": { de: "Übersetzung", en: "Translation" },
  "nav.rechtsprechung": { de: "Rechtsprechung", en: "Case Law" },
  "nav.norms": { de: "Normen", en: "Statutes" },
  "nav.judgements_sync": { de: "Urteile-Sync", en: "Judgements Sync" },
  "nav.kollisionspruefung": { de: "Kollisionsprüfung", en: "Conflict Check" },
  "nav.tabular_review": { de: "Massen-Review", en: "Bulk Review" },
  "nav.obligation_tracking": { de: "Obligation Tracking", en: "Obligation Tracking" },
  "nav.case_scanner": { de: "Akten-Scanner", en: "Case Scanner" },
  "nav.clause_library": { de: "Klausel-Bibliothek", en: "Clause Library" },
  "nav.review_queue": { de: "Review-Queue", en: "Review Queue" },
  "nav.version_history": { de: "Versionshistorie", en: "Version History" },
  "nav.monitoring": { de: "Monitoring", en: "Monitoring" },
  "nav.sources": { de: "Rechtsquellen", en: "Legal Sources" },

  // ── Sidebar: nav items (drafts & billing) ──
  "nav.drafting": { de: "Schriftsatz", en: "Drafting" },
  "nav.cost_calculator": { de: "Kostenrechner", en: "Cost Calculator" },
  "nav.invoicing": { de: "Rechnungen", en: "Invoices" },
  "nav.datev_export": { de: "DATEV-Export", en: "DATEV Export" },
  "nav.signature": { de: "e-Signatur", en: "e-Signature" },

  // ── Sidebar: nav items (data & integration) ──
  "nav.connectors": { de: "Konnektoren", en: "Connectors" },
  "nav.whatsapp": { de: "WhatsApp", en: "WhatsApp" },
  "nav.import_kanzlei": { de: "Kanzlei-Import", en: "Firm Import" },
  "nav.bea": { de: "beA", en: "beA" },
  "nav.email_import": { de: "E-Mail-Import", en: "Email Import" },
  "nav.calendar_export": { de: "Kalender", en: "Calendar" },
  "nav.compliance": { de: "Compliance", en: "Compliance" },
  "nav.retention": { de: "Löschfristen", en: "Retention Rules" },
  "nav.anonymize": { de: "Anonymisierung", en: "Anonymization" },
  "nav.word_addin": { de: "Word Add-in", en: "Word Add-in" },
  "nav.verfahrensdoku": { de: "Verfahrensdoku", en: "Process Documentation" },
  "nav.data_export": { de: "Datenexport", en: "Data Export" },

  // ── Sidebar: nav items (industries — coming soon) ──
  "nav.consulting": { de: "Consulting", en: "Consulting" },
  "nav.insurance": { de: "Versicherung", en: "Insurance" },
  "nav.medical": { de: "Medizin", en: "Medical" },
  "nav.realestate": { de: "Immobilien", en: "Real Estate" },
  "nav.recruiting": { de: "Recruiting", en: "Recruiting" },
  "nav.tax": { de: "Steuer", en: "Tax" },
  "nav.vc": { de: "VC", en: "VC" },

  // ── Sidebar: bottom items ──
  "nav.team": { de: "Team", en: "Team" },
  "nav.controlling": { de: "Controlling", en: "Controlling" },
  "nav.audit_log": { de: "Audit-Log", en: "Audit Log" },
  "nav.api_keys": { de: "API-Keys", en: "API Keys" },
  "nav.billing": { de: "Abrechnung", en: "Billing" },
  "nav.mobile": { de: "Mobile", en: "Mobile" },
  "nav.settings": { de: "Settings", en: "Settings" },
  "nav.kanzlei": { de: "Kanzlei", en: "Firm" },
  "nav.security": { de: "Sicherheit", en: "Security" },

  // ── Sidebar: UI strings ──
  "sidebar.brain_status": { de: "Brain Status", en: "Brain Status" },
  "sidebar.active": { de: "Active", en: "Active" },
  "sidebar.pages_entities": { de: "pages", en: "pages" },
  "sidebar.changes_pending": { de: "Änderung(en) ausstehend", en: "change(s) pending" },
  "sidebar.sync_now": { de: "Jetzt syncen", en: "Sync now" },
  "sidebar.syncing": { de: "Sync…", en: "Syncing…" },
  "sidebar.offline_tooltip": {
    de: "Offline — Änderungen werden lokal zwischengespeichert",
    en: "Offline — changes are cached locally",
  },
  "sidebar.offline": { de: "Offline", en: "Offline" },
  "sidebar.filter_placeholder": { de: "Navigation filtern…", en: "Filter navigation…" },
  "sidebar.no_results": { de: "Keine Treffer für", en: "No results for" },
  "sidebar.dream_cycle": { de: "Dream Cycle", en: "Dream Cycle" },
  "sidebar.dream_last_run": { de: "Letzter Lauf:", en: "Last run:" },
  "sidebar.dream_not_scheduled": {
    de: "Nächtliche Konsolidierung — noch nicht geplant",
    en: "Nightly consolidation — not scheduled yet",
  },
  "sidebar.collapse": { de: "Einklappen", en: "Collapse" },
  "sidebar.expand": { de: "Sidebar ausklappen", en: "Expand sidebar" },
  "sidebar.collapse_aria": { de: "Sidebar einklappen", en: "Collapse sidebar" },
  "sidebar.close_menu": { de: "Menü schließen", en: "Close menu" },
  "sidebar.coming_soon": { de: "bald", en: "soon" },
  "sidebar.user": { de: "Benutzer", en: "User" },
  "sidebar.main_nav": { de: "Hauptnavigation", en: "Main navigation" },

  // ── Topbar ──
  "topbar.search_placeholder": { de: "Brain durchsuchen…", en: "Search brain…" },
  "topbar.search_aria": { de: "Brain durchsuchen", en: "Search brain" },
  "topbar.theme_light": { de: "Zu hellem Design wechseln", en: "Switch to light theme" },
  "topbar.theme_dark": { de: "Zu dunklem Design wechseln", en: "Switch to dark theme" },
  "topbar.theme_light_aria": { de: "Helles Design aktivieren", en: "Activate light theme" },
  "topbar.theme_dark_aria": { de: "Dunkles Design aktivieren", en: "Activate dark theme" },
  "topbar.notifications": { de: "Benachrichtigungen", en: "Notifications" },
  "topbar.close": { de: "Schließen", en: "Close" },
  "topbar.no_notifications": { de: "Keine neuen Benachrichtigungen", en: "No new notifications" },
  "topbar.user_menu": { de: "Benutzermenü", en: "User menu" },
  "topbar.open_menu": { de: "Menü öffnen", en: "Open menu" },
  "topbar.user_fallback": { de: "Benutzer", en: "User" },
  "topbar.settings": { de: "Einstellungen", en: "Settings" },
  "topbar.logout": { de: "Abmelden", en: "Log out" },
  "topbar.brain_selector_aria": { de: "Aktiven Brain wechseln", en: "Switch active brain" },
  "topbar.notif_deadline_soon": { de: "Frist bald fällig", en: "Deadline approaching" },
  "topbar.notif_deadline_overdue": { de: "Frist überfällig", en: "Deadline overdue" },
  "topbar.notif_days": { de: "Tage", en: "days" },
  "topbar.notif_days_overdue": { de: "Tage überfällig", en: "days overdue" },
  "topbar.notif_dream_last": { de: "Letzter Lauf: vor", en: "Last run:" },
  "topbar.notif_dream_hours": { de: "Stunden", en: "hours" },

  // ── Dashboard page ──
  "dashboard.title": { de: "Dashboard", en: "Dashboard" },
  "dashboard.desc_loading": { de: "Lade Brain-Status…", en: "Loading brain status…" },
  "dashboard.desc_online": {
    de: "Verbunden — frag dein Brain oder lade Akten hoch",
    en: "Connected — query your brain or upload documents",
  },
  "dashboard.desc_offline": {
    de: "Engine nicht erreichbar — Verbindung prüfen",
    en: "Engine unreachable — check connection",
  },
  "dashboard.connected": { de: "Verbunden", en: "Connected" },
  "dashboard.offline": { de: "Offline", en: "Offline" },
  "dashboard.add_document": { de: "Dokument hinzufügen", en: "Add document" },
  "dashboard.stat_pages": { de: "Seiten", en: "Pages" },
  "dashboard.stat_entities": { de: "Entitäten", en: "Entities" },
  "dashboard.stat_edges": { de: "Graph-Kanten", en: "Graph Edges" },
  "dashboard.stat_queries": { de: "Queries heute", en: "Queries today" },
  "dashboard.stat_statutes": { de: "Gesetze", en: "Statutes" },
  "dashboard.getting_started": { de: "Erste Schritte", en: "Getting started" },
  "dashboard.gs_upload": { de: "Erste Akte hochladen", en: "Upload first document" },
  "dashboard.gs_upload_desc": {
    de: "PDF/Dokument wird geparst, indexiert und embedded",
    en: "PDF/document is parsed, indexed and embedded",
  },
  "dashboard.gs_upload_btn": { de: "Hochladen", en: "Upload" },
  "dashboard.gs_query": { de: "Erste Frage stellen", en: "Ask first question" },
  "dashboard.gs_query_desc": {
    de: "Belegte KI-Antwort mit Fundstellen",
    en: "Cited AI answer with sources",
  },
  "dashboard.gs_query_btn": { de: "Fragen", en: "Ask" },
  "dashboard.gs_graph": { de: "Wissensgraph erkunden", en: "Explore knowledge graph" },
  "dashboard.gs_graph_desc": {
    de: "Verbindungen zwischen Akten, Personen, Fristen",
    en: "Connections between cases, people, deadlines",
  },
  "dashboard.gs_graph_btn": { de: "Graph öffnen", en: "Open graph" },
  "dashboard.recent_activity": { de: "Letzte Aktivität", en: "Recent activity" },
  "dashboard.show_all": { de: "Alle anzeigen", en: "Show all" },
  "dashboard.no_activity": { de: "Noch keine Aktivität", en: "No activity yet" },
  "dashboard.no_activity_desc": {
    de: "Lade ein Dokument hoch oder stelle eine Frage, um zu starten",
    en: "Upload a document or ask a question to get started",
  },
  "dashboard.quick_actions": { de: "Schnellzugriff", en: "Quick actions" },
  "dashboard.qa_upload": { de: "Dokument hochladen", en: "Upload document" },
  "dashboard.qa_upload_desc": { de: "PDF, Markdown oder Text", en: "PDF, Markdown or text" },
  "dashboard.qa_query": { de: "Brain fragen", en: "Ask brain" },
  "dashboard.qa_query_desc": { de: "KI-Synthese starten", en: "Start AI synthesis" },
  "dashboard.qa_explore": { de: "Brain erkunden", en: "Explore brain" },
  "dashboard.qa_explore_desc": { de: "Seiten & Entitäten", en: "Pages & entities" },
  "dashboard.qa_graph": { de: "Graph ansehen", en: "View graph" },
  "dashboard.qa_graph_desc": { de: "Wissensstruktur", en: "Knowledge structure" },
  "dashboard.upcoming_deadlines": { de: "Anstehende Fristen", en: "Upcoming deadlines" },
  "dashboard.all": { de: "Alle", en: "All" },
  "dashboard.no_deadlines": { de: "Keine Fristen in nächster Zeit", en: "No upcoming deadlines" },
  "dashboard.today": { de: "Heute", en: "Today" },
  "dashboard.overdue_short": { de: "überfällig", en: "overdue" },
  "dashboard.dream_cycle": { de: "Dream Cycle", en: "Dream Cycle" },
  "dashboard.dream_inactive": { de: "Inaktiv", en: "Inactive" },
  "dashboard.dream_desc": {
    de: "Der Dream Cycle läuft nachts und konsolidiert dein Wissen, fixiert Zitate und findet Widersprüche.",
    en: "The Dream Cycle runs at night, consolidates your knowledge, fixes citations and finds contradictions.",
  },
  "dashboard.dream_setup": { de: "Dream Cycle einrichten", en: "Set up Dream Cycle" },
  "dashboard.welcome": { de: "Willkommen bei Subsumio!", en: "Welcome to Subsumio!" },
  "dashboard.welcome_desc": {
    de: "Dein Brain ist bereit. In 3 Schritten startest du: lade ein Dokument hoch, stelle eine Frage und erkunde deinen Wissensgraphen.",
    en: "Your brain is ready. Get started in 3 steps: upload a document, ask a question and explore your knowledge graph.",
  },
  "dashboard.welcome_upload": { de: "Erstes Dokument hochladen", en: "Upload first document" },
  "dashboard.welcome_ask": { de: "Brain fragen", en: "Ask brain" },
  "dashboard.error_load": {
    de: "Brain-Status konnte nicht geladen werden.",
    en: "Failed to load brain status.",
  },
  "dashboard.error_engine": {
    de: "Engine oder Netzwerk ist nicht erreichbar.",
    en: "Engine or network is unreachable.",
  },
  "dashboard.retry": { de: "Erneut versuchen", en: "Retry" },
  "dashboard.unnamed_deadline": { de: "Unbenannte Frist", en: "Untitled deadline" },
  "dashboard.time_now": { de: "gerade eben", en: "just now" },
  "dashboard.time_min": { de: "vor", en: "" },
  "dashboard.time_min_suffix": { de: "Min", en: "min ago" },
  "dashboard.time_hour_suffix": { de: "Std", en: "h ago" },
  "dashboard.time_day": { de: "vor", en: "" },
  "dashboard.time_day_suffix": { de: "Tag", en: "day ago" },
  "dashboard.time_days_suffix": { de: "Tagen", en: "days ago" },

  // ── Cases page ──
  "cases.title": { de: "Akten", en: "Cases" },
  "cases.count": { de: "Akten im Brain", en: "cases in brain" },
  "cases.new": { de: "Neue Akte", en: "New case" },
  "cases.all": { de: "Alle", en: "All" },
  "cases.search": { de: "Akten suchen…", en: "Search cases…" },
  "cases.error_offline": {
    de: "Cloud-Brain gerade nicht erreichbar. Es werden zwischengespeicherte Akten angezeigt.",
    en: "Cloud brain unavailable. Showing cached cases.",
  },
  "cases.error_load": { de: "Akten konnten nicht geladen werden.", en: "Failed to load cases." },
  "cases.retry": { de: "Erneut versuchen", en: "Retry" },
  "cases.empty_title": { de: "Keine Akten gefunden", en: "No cases found" },
  "cases.empty_no_cases": {
    de: "Erstelle deine erste Akte oder importiere bestehende Fälle.",
    en: "Create your first case or import existing ones.",
  },
  "cases.empty_filtered": { de: "Passe deine Filter an.", en: "Adjust your filters." },
  "cases.empty_create": { de: "Neue Akte erstellen", en: "Create new case" },
  "cases.bulk_delete": { de: "Auswahl löschen", en: "Delete selection" },
  "cases.col_title": { de: "Akte", en: "Case" },
  "cases.col_status": { de: "Status", en: "Status" },
  "cases.col_priority": { de: "Priorität", en: "Priority" },
  "cases.col_legal_area": { de: "Rechtsgebiet", en: "Legal area" },
  "cases.col_opponent": { de: "Gegner", en: "Opponent" },
  "cases.col_updated": { de: "Aktualisiert", en: "Updated" },
  "cases.delete": { de: "Akte löschen", en: "Delete case" },
  "cases.status_open": { de: "Offen", en: "Open" },
  "cases.status_pending": { de: "Anhängig", en: "Pending" },
  "cases.status_settled": { de: "Erledigt", en: "Settled" },
  "cases.status_won": { de: "Gewonnen", en: "Won" },
  "cases.status_lost": { de: "Verloren", en: "Lost" },
  "cases.status_appealed": { de: "Berufung", en: "Appealed" },
  "cases.status_dormant": { de: "Ruhend", en: "Dormant" },
  "cases.toast_deleted": { de: "Akte gelöscht", en: "Case deleted" },
  "cases.toast_deleted_desc": { de: "Akte entfernt", en: "Case removed" },
  "cases.toast_delete_fail": { de: "Löschen fehlgeschlagen", en: "Delete failed" },
  "cases.toast_bulk_deleted": { de: "Akten gelöscht", en: "cases deleted" },
  "cases.toast_bulk_fail": { de: "Massenlöschung fehlgeschlagen", en: "Bulk delete failed" },
  "cases.unknown_error": { de: "Unbekannter Fehler", en: "Unknown error" },

  // ── Deadlines page ──
  "deadlines.title": { de: "Fristen & Termine", en: "Deadlines & Events" },
  "deadlines.count": { de: "Fristen aus allen Akten", en: "deadlines from all cases" },
  "deadlines.send_reminders": { de: "Erinnerungen senden", en: "Send reminders" },
  "deadlines.calculate": { de: "Frist berechnen", en: "Calculate deadline" },
  "deadlines.detect": { de: "Fristen erkennen", en: "Detect deadlines" },
  "deadlines.calc_title": { de: "Fristenberechnung", en: "Deadline calculation" },
  "deadlines.calc_type": { de: "Frist-Typ", en: "Deadline type" },
  "deadlines.calc_start_date": {
    de: "Startdatum (Zustellung / Ereignis)",
    en: "Start date (service / event)",
  },
  "deadlines.calc_button": { de: "Berechnen", en: "Calculate" },
  "deadlines.calc_due": { de: "Frist bis:", en: "Deadline:" },
  "deadlines.calc_remaining": { de: "Tage verbleibend", en: "days remaining" },
  "deadlines.detect_title": { de: "Fristen erkennen", en: "Detect deadlines" },
  "deadlines.detect_desc": {
    de: "Fügen Sie einen Text (E-Mail, Brief, Gerichtsbescheid) ein. Die KI erkennt automatisch Fristen, Termine und gesetzliche Deadlines und schlägt deren Anlage vor.",
    en: "Paste text (email, letter, court notice). AI automatically detects deadlines, dates and statutory deadlines and suggests creating them.",
  },
  "deadlines.detect_placeholder": { de: "Text hier einfügen…", en: "Paste text here…" },
  "deadlines.detect_analyzing": { de: "Analysiere…", en: "Analyzing…" },
  "deadlines.detect_button": { de: "Fristen erkennen", en: "Detect deadlines" },
  "deadlines.detect_result": { de: "Frist(en) erkannt", en: "deadline(s) detected" },
  "deadlines.alert_critical": { de: "kritische Frist", en: "critical deadline" },
  "deadlines.alert_critical_plural": { de: "kritische Fristen", en: "critical deadlines" },
  "deadlines.alert_in_days": { de: "in den nächsten 3 Tagen", en: "in the next 3 days" },
  "deadlines.all": { de: "Alle", en: "All" },
  "deadlines.search": { de: "Fristen suchen…", en: "Search deadlines…" },
  "deadlines.error_offline": {
    de: "Cloud-Brain gerade nicht erreichbar. Es werden zwischengespeicherte Fristen angezeigt.",
    en: "Cloud brain unavailable. Showing cached deadlines.",
  },
  "deadlines.error_load": {
    de: "Fristen konnten nicht geladen werden.",
    en: "Failed to load deadlines.",
  },
  "deadlines.retry": { de: "Erneut versuchen", en: "Retry" },
  "deadlines.empty_title": { de: "Keine Fristen gefunden", en: "No deadlines found" },
  "deadlines.empty_no_data": {
    de: "Fristen werden automatisch aus hochgeladenen Dokumenten extrahiert.",
    en: "Deadlines are automatically extracted from uploaded documents.",
  },
  "deadlines.empty_filtered": { de: "Passe deine Filter an.", en: "Adjust your filters." },
  "deadlines.col_title": { de: "Frist", en: "Deadline" },
  "deadlines.col_case": { de: "Akte", en: "Case" },
  "deadlines.col_date": { de: "Datum", en: "Date" },
  "deadlines.today": { de: "Heute", en: "Today" },
  "deadlines.tomorrow": { de: "Morgen", en: "Tomorrow" },
  "deadlines.in_days": { de: "in", en: "in" },
  "deadlines.days": { de: "Tagen", en: "days" },
  "deadlines.days_overdue": { de: "Tage überfällig", en: "days overdue" },
  "deadlines.status_pending": { de: "Ausstehend", en: "Pending" },
  "deadlines.status_warning": { de: "Bald fällig", en: "Due soon" },
  "deadlines.status_critical": { de: "Kritisch", en: "Critical" },
  "deadlines.status_overdue": { de: "Überfällig", en: "Overdue" },
  "deadlines.status_done": { de: "Erledigt", en: "Done" },
  "deadlines.type_deadline": { de: "Frist", en: "Deadline" },
  "deadlines.type_event": { de: "Termin", en: "Event" },
  "deadlines.type_hearing": { de: "Verhandlung", en: "Hearing" },
  "deadlines.type_filing": { de: "Schriftstück", en: "Filing" },
  "deadlines.review_approved": { de: "Freigegeben", en: "Approved" },
  "deadlines.review_open": { de: "Review offen", en: "Review pending" },
  "deadlines.toast_sending": { de: "Sende Erinnerungen…", en: "Sending reminders…" },
  "deadlines.toast_sent": { de: "Erinnerung(en) gesendet", en: "reminder(s) sent" },
  "deadlines.toast_smtp": { de: "SMTP nicht konfiguriert", en: "SMTP not configured" },
  "deadlines.toast_fail": { de: "Senden fehlgeschlagen", en: "Sending failed" },
  "deadlines.error_prefix": { de: "Fehler", en: "Error" },

  // ── Invoicing page ──
  "inv.title": { de: "Rechnungen", en: "Invoices" },
  "inv.desc": { de: "Abrechnung & PDF-Export", en: "Billing & PDF export" },
  "inv.cancel": { de: "Abbrechen", en: "Cancel" },
  "inv.create": { de: "Rechnung erstellen", en: "Create invoice" },
  "inv.outstanding": { de: "Offen", en: "Outstanding" },
  "inv.paid": { de: "Bezahlt", en: "Paid" },
  "inv.invoices": { de: "Rechnungen", en: "Invoices" },
  "inv.create_from_case": { de: "Rechnung aus Akte erstellen", en: "Create invoice from case" },
  "inv.select_case": { de: "Akte wählen", en: "Select case" },
  "inv.select_case_placeholder": { de: "— Akte auswählen —", en: "— Select case —" },
  "inv.invoice_type": { de: "Rechnungstyp", en: "Invoice type" },
  "inv.type_standard": { de: "Standard", en: "Standard" },
  "inv.type_teilrechnung": { de: "Teilrechnung", en: "Partial invoice" },
  "inv.type_sammelrechnung": { de: "Sammelrechnung", en: "Summary invoice" },
  "inv.type_gutschrift": { de: "Gutschrift", en: "Credit note" },
  "inv.no_billable": {
    de: "Keine offenen abrechenbaren Zeiten oder Auslagen in dieser Akte.",
    en: "No open billable time or expenses in this case.",
  },
  "inv.open_bookings": { de: "offene Buchungen", en: "open entries" },
  "inv.expenses": { de: "Auslagen", en: "Expenses" },
  "inv.fee_estimated": { de: "Honorar geschätzt:", en: "Estimated fee:" },
  "inv.advance_payment": { de: "Vorschuss / Anzahlung (€)", en: "Advance payment (€)" },
  "inv.search": { de: "Rechnung suchen…", en: "Search invoice…" },
  "inv.empty_title": { de: "Keine Rechnungen", en: "No invoices" },
  "inv.empty_desc": {
    de: "Erstellen Sie eine Rechnung aus einer Akte mit Zeiterfassung.",
    en: "Create an invoice from a case with time tracking.",
  },
  "inv.status_draft": { de: "Entwurf", en: "Draft" },
  "inv.status_sent": { de: "Gesendet", en: "Sent" },
  "inv.status_paid": { de: "Bezahlt", en: "Paid" },
  "inv.status_overdue": { de: "Überfällig", en: "Overdue" },
  "inv.status_cancelled": { de: "Storniert", en: "Cancelled" },
  "inv.reminder": { de: "Mahnung", en: "Reminder" },
  "inv.positions": { de: "Positionen", en: "items" },
  "inv.incl_vat": { de: "inkl. MwSt.", en: "incl. VAT" },
  "inv.print": { de: "Drucken", en: "Print" },
  "inv.download_pdf": { de: "PDF herunterladen", en: "Download PDF" },
  "inv.send_email": { de: "Per E-Mail senden", en: "Send by email" },
  "inv.mark_sent": { de: "Als gesendet markieren", en: "Mark as sent" },
  "inv.mark_paid": { de: "Als bezahlt markieren", en: "Mark as paid" },
  "inv.cancel_invoice": { de: "Stornieren", en: "Cancel" },
  "inv.send_reminder": { de: "Mahnung senden", en: "Send reminder" },
  "inv.delete": { de: "Löschen", en: "Delete" },
  "inv.confirm_delete_title": { de: "Rechnung löschen", en: "Delete invoice" },
  "inv.confirm_delete_msg": { de: "Möchten Sie Rechnung", en: "Do you want to delete invoice" },
  "inv.confirm_delete_confirm": { de: "Löschen", en: "Delete" },
  "inv.error_offline": {
    de: "Cloud-Brain gerade nicht erreichbar. Es werden zwischengespeicherte Rechnungen angezeigt.",
    en: "Cloud brain unavailable. Showing cached invoices.",
  },
  "inv.email_sending": { de: "E-Mail wird gesendet…", en: "Sending email…" },
  "inv.email_sent": { de: "E-Mail gesendet an", en: "Email sent to" },
  "inv.email_smtp_error": {
    de: "SMTP nicht konfiguriert. Bitte in Einstellungen → Kanzlei hinterlegen.",
    en: "SMTP not configured. Set up in Settings → Firm.",
  },
  "inv.email_fail": { de: "Senden fehlgeschlagen.", en: "Sending failed." },
  "inv.reminder_sending": { de: "Mahnung wird gesendet…", en: "Sending reminder…" },
  "inv.reminder_sent": { de: "Mahnung gesendet", en: "Reminder sent" },
  "inv.reminder_fee": { de: "Gebühr:", en: "Fee:" },
  "inv.reminder_fail": { de: "Mahnung fehlgeschlagen.", en: "Reminder failed." },
  "inv.updated": { de: "wurde aktualisiert.", en: "has been updated." },
  "inv.status_save_fail": {
    de: "Status konnte nicht gespeichert werden.",
    en: "Status could not be saved.",
  },
  "inv.deleted": { de: "gelöscht.", en: "deleted." },
  "inv.delete_fail": { de: "Löschen fehlgeschlagen.", en: "Delete failed." },
  "inv.unknown_client": { de: "Unbekannter Mandant", en: "Unknown client" },
  "inv.rvg_calculate": { de: "RVG berechnen", en: "Calculate RVG" },
  "inv.rvg_title": { de: "RVG-Gebührenberechnung", en: "RVG fee calculation" },
  "inv.rvg_streitwert": { de: "Streitwert (€)", en: "Dispute value (€)" },
  "inv.rvg_basis": { de: "Basisgebühr (1,0)", en: "Base fee (1.0)" },
  "inv.rvg_verfahren": { de: "Verfahrensgebühr (1,3)", en: "Proceedings fee (1.3)" },
  "inv.rvg_termins": { de: "Terminsgebühr (1,2)", en: "Hearing fee (1.2)" },
  "inv.rvg_auslagen": { de: "Auslagenpauschale", en: "Lump-sum expenses" },
  "inv.rvg_netto": { de: "Netto", en: "Net" },
  "inv.rvg_vat": { de: "MwSt (19 %)", en: "VAT (19%)" },
  "inv.rvg_brutto": { de: "Brutto", en: "Gross" },
  "inv.rvg_close": { de: "Schließen", en: "Close" },
  "inv.admin_lawyer_only": { de: "Nur Admin oder Anwalt", en: "Admin or lawyer only" },
  "inv.days_net": { de: "Tage netto", en: "days net" },
  "inv.invoice_for_case": { de: "Rechnung für Akte", en: "Invoice for case" },
  "inv.paid_on": { de: "bezahlt", en: "paid on" },
  "inv.loading": { de: "Lädt", en: "Loading" },
  "inv.error_prefix": { de: "Fehler", en: "Error" },

  // ── Settings page ──
  "settings.title": { de: "Einstellungen", en: "Settings" },
  "settings.desc": {
    de: "Subsumio Engine & Dashboard konfigurieren",
    en: "Configure Subsumio engine & dashboard",
  },
  "settings.tab_brain": { de: "Brain", en: "Brain" },
  "settings.tab_api": { de: "API Keys", en: "API Keys" },
  "settings.tab_dream": { de: "Dream Cycle", en: "Dream Cycle" },
  "settings.tab_kanzlei": { de: "Kanzlei", en: "Firm" },
  "settings.tab_team": { de: "Team", en: "Team" },
  "settings.tab_account": { de: "Account", en: "Account" },
  "settings.brain_config": { de: "Brain-Konfiguration", en: "Brain configuration" },
  "settings.engine_url": { de: "Engine-URL", en: "Engine URL" },
  "settings.engine_url_desc": {
    de: "URL des laufenden Subsumio-Engine-Servers",
    en: "URL of the running Subsumio engine server",
  },
  "settings.connection_status": { de: "Verbindungsstatus", en: "Connection status" },
  "settings.connection_desc": {
    de: "Prüft ob die Subsumio Engine erreichbar ist",
    en: "Checks if the Subsumio engine is reachable",
  },
  "settings.checking": { de: "Prüfe…", en: "Checking…" },
  "settings.connected": { de: "Verbunden", en: "Connected" },
  "settings.not_connected": { de: "Nicht verbunden", en: "Not connected" },
  "settings.connect": { de: "Verbinden", en: "Connect" },
  "settings.search_mode": { de: "Suche-Modus", en: "Search mode" },
  "settings.search_mode_desc": {
    de: "Qualitäts-/Kosten-Tradeoff für Hybrid-Suche",
    en: "Quality/cost tradeoff for hybrid search",
  },
  "settings.start_engine": { de: "Engine starten", en: "Start engine" },
  "settings.start_engine_desc": {
    de: "Befehle zum Starten der lokalen Subsumio Engine",
    en: "Commands to start the local Subsumio engine",
  },
  "settings.api_keys": { de: "API Keys", en: "API Keys" },
  "settings.api_keys_desc": {
    de: "Keys werden lokal gespeichert und nie an Server gesendet.",
    en: "Keys are stored locally and never sent to the server.",
  },
  "settings.openai_key": { de: "OpenAI API Key", en: "OpenAI API Key" },
  "settings.openai_key_desc": {
    de: "Für Embeddings und Synthese (text-embedding-3-small)",
    en: "For embeddings and synthesis (text-embedding-3-small)",
  },
  "settings.create_key": { de: "API Key erstellen", en: "Create API key" },
  "settings.anthropic_key": { de: "Anthropic API Key", en: "Anthropic API Key" },
  "settings.anthropic_key_desc": {
    de: "Für KI-Synthese (Claude 3.5 Sonnet)",
    en: "For AI synthesis (Claude 3.5 Sonnet)",
  },
  "settings.zeroentropy_key": { de: "ZeroEntropy API Key", en: "ZeroEntropy API Key" },
  "settings.zeroentropy_key_desc": {
    de: "Optionaler Reranker für höhere Suchqualität (+P@5)",
    en: "Optional reranker for higher search quality (+P@5)",
  },
  "settings.zeroentropy_badge": {
    de: "Optional — verbessert Recall deutlich",
    en: "Optional — significantly improves recall",
  },
  "settings.saved": { de: "Gespeichert", en: "Saved" },
  "settings.save_keys": { de: "Keys speichern", en: "Save keys" },
  "settings.dream_title": { de: "Dream Cycle", en: "Dream Cycle" },
  "settings.dream_desc": {
    de: "Nächtliche Konsolidierung & Enrichment",
    en: "Nightly consolidation & enrichment",
  },
  "settings.active": { de: "Aktiv", en: "Active" },
  "settings.inactive": { de: "Inaktiv", en: "Inactive" },
  "settings.dream_enable": { de: "Dream Cycle aktivieren", en: "Enable Dream Cycle" },
  "settings.dream_enable_desc": { de: "Täglich um 3:00 Uhr morgens", en: "Daily at 3:00 AM" },
  "settings.dream_running": { de: "Läuft täglich um 3:00 Uhr", en: "Runs daily at 3:00 AM" },
  "settings.dream_disabled": { de: "Deaktiviert", en: "Disabled" },
  "settings.dream_what": {
    de: "Was passiert im Dream Cycle",
    en: "What happens in the Dream Cycle",
  },
  "settings.dream_task_1": {
    de: "Duplikate in Personen- und Firmen-Seiten erkennen & mergen",
    en: "Detect & merge duplicates in person and company pages",
  },
  "settings.dream_task_2": {
    de: "Kaputte Zitate reparieren und neu verlinken",
    en: "Fix broken citations and re-link",
  },
  "settings.dream_task_3": {
    de: "Salience Score für alle Seiten berechnen",
    en: "Calculate salience score for all pages",
  },
  "settings.dream_task_4": {
    de: "Widersprüche in Fakten markieren",
    en: "Flag contradictions in facts",
  },
  "settings.dream_task_5": {
    de: "Aufgaben für den nächsten Tag vorbereiten",
    en: "Prepare tasks for the next day",
  },
  "settings.kanzlei_title": { de: "Kanzlei-Einstellungen", en: "Firm settings" },
  "settings.kanzlei_desc": {
    de: "Verrechnung, Stundensatz & Abrechnung",
    en: "Billing, hourly rate & invoicing",
  },
  "settings.kanzlei_name": { de: "Kanzlei-Name", en: "Firm name" },
  "settings.kanzlei_name_desc": {
    de: "Für Rechnungskopf und Mandanten-Portal",
    en: "For invoice header and client portal",
  },
  "settings.anwalt_name": { de: "Anwalt / Rechnungssteller", en: "Lawyer / invoicer" },
  "settings.anwalt_name_desc": {
    de: "Name des Anwalts auf der Rechnung",
    en: "Lawyer name on the invoice",
  },
  "settings.kanzlei_address": { de: "Kanzlei-Adresse", en: "Firm address" },
  "settings.kanzlei_address_desc": {
    de: "Absender und Rechnungskopf",
    en: "Sender and invoice header",
  },
  "settings.contact": { de: "Kontakt", en: "Contact" },
  "settings.contact_desc": {
    de: "Telefon, E-Mail und Kammer-/Registerangabe",
    en: "Phone, email and chamber/registry details",
  },
  "settings.ust_id": { de: "USt-ID-Nr.", en: "VAT ID" },
  "settings.ust_id_desc": {
    de: "Für DATEV-Export und Rechnungen (z. B. DE123456789)",
    en: "For DATEV export and invoices (e.g. DE123456789)",
  },
  "settings.tarif_model": { de: "Tarifmodell", en: "Fee model" },
  "settings.tarif_model_desc": {
    de: "Basis für Gebührenberechnung und Verrechnung",
    en: "Basis for fee calculation and billing",
  },
  "settings.tarif_custom": { de: "Freier Satz", en: "Custom rate" },
  "settings.tarif_rvg": { de: "RVG (Deutschland)", en: "RVG (Germany)" },
  "settings.tarif_ratg": { de: "RATG (Österreich)", en: "RATG (Austria)" },
  "settings.hourly_rate": { de: "Stundensatz (€)", en: "Hourly rate (€)" },
  "settings.hourly_rate_desc": {
    de: "Standard-Satz für Zeiterfassung",
    en: "Default rate for time tracking",
  },
  "settings.per_hour": { de: "/ Stunde", en: "/ hour" },
  "settings.billing_increment": { de: "Min.-Takt", en: "Min. increment" },
  "settings.rates_per_area": {
    de: "Stundensätze pro Rechtsgebiet",
    en: "Hourly rates per legal area",
  },
  "settings.rates_per_area_desc": {
    de: "Spezifische Sätze je nach Materie",
    en: "Specific rates per practice area",
  },
  "settings.bank_details": { de: "Bankverbindung", en: "Bank details" },
  "settings.bank_details_desc": {
    de: "Für den Rechnungsfuß und Zahlungsabgleich",
    en: "For invoice footer and payment matching",
  },
  "settings.payment_terms": { de: "Zahlungsziel", en: "Payment terms" },
  "settings.payment_terms_desc": {
    de: "Standard-Fälligkeit neuer Rechnungen",
    en: "Default due date for new invoices",
  },
  "settings.days_net": { de: "Tage netto", en: "days net" },
  "settings.invoice_footer": { de: "Rechnungsfuß", en: "Invoice footer" },
  "settings.invoice_footer_desc": {
    de: "Hinweistext unter der Rechnung",
    en: "Notice text below the invoice",
  },
  "settings.datev_chart": { de: "DATEV Kontenrahmen", en: "DATEV chart of accounts" },
  "settings.datev_chart_desc": {
    de: "Für DATEV Unternehmen Online Export",
    en: "For DATEV Unternehmen Online export",
  },
  "settings.datev_consultant": { de: "DATEV Berater-Nr.", en: "DATEV consultant no." },
  "settings.datev_consultant_desc": {
    de: "Ihre Steuerberater-Nummer für DATEV",
    en: "Your tax consultant number for DATEV",
  },
  "settings.datev_client": { de: "DATEV Mandanten-Nr.", en: "DATEV client no." },
  "settings.datev_client_desc": {
    de: "Ihre Mandanten-Nummer beim Steuerberater",
    en: "Your client number at the tax consultant",
  },
  "settings.smtp_server": { de: "SMTP-Server", en: "SMTP server" },
  "settings.smtp_server_desc": {
    de: "E-Mail-Versand (z. B. mail.example.com)",
    en: "Email sending (e.g. mail.example.com)",
  },
  "settings.smtp_user": { de: "SMTP-Benutzer", en: "SMTP user" },
  "settings.smtp_user_desc": { de: "Login für den E-Mail-Versand", en: "Login for email sending" },
  "settings.smtp_password": { de: "SMTP-Passwort", en: "SMTP password" },
  "settings.smtp_password_desc": {
    de: "Passwort oder App-Passwort",
    en: "Password or app password",
  },
  "settings.email_from": { de: "Absender-Adresse", en: "Sender address" },
  "settings.email_from_desc": {
    de: "E-Mail-Adresse im From-Feld",
    en: "Email address in the From field",
  },
  "settings.save_fail": { de: "Speichern fehlgeschlagen:", en: "Save failed:" },
  "settings.save": { de: "Einstellungen speichern", en: "Save settings" },
  "settings.kanzlei_save_fail": {
    de: "Kanzlei-Einstellungen konnten nicht gespeichert werden.",
    en: "Firm settings could not be saved.",
  },
  "settings.team_title": { de: "Team", en: "Team" },
  "settings.team_desc": { de: "Kanzlei-Mitarbeiter und Rollen", en: "Firm staff and roles" },
  "settings.team_empty": { de: "Keine Team-Mitglieder gefunden.", en: "No team members found." },
  "settings.role_admin": { de: "Admin", en: "Admin" },
  "settings.role_lawyer": { de: "Anwalt", en: "Lawyer" },
  "settings.role_assistant": { de: "Sekretariat", en: "Assistant" },
  "settings.role_client_viewer": { de: "Client Viewer", en: "Client Viewer" },
  "settings.account_title": { de: "Account", en: "Account" },
  "settings.plan": { de: "Plan", en: "Plan" },
  "settings.plan_desc": { de: "Dein aktuelles Abonnement", en: "Your current subscription" },
  "settings.upgrade": { de: "Upgrade auf Pro →", en: "Upgrade to Pro →" },
  "settings.usage": { de: "Nutzung", en: "Usage" },
  "settings.usage_desc": { de: "Aktueller Monat", en: "Current month" },
  "settings.usage_pages": { de: "Seiten", en: "Pages" },
  "settings.usage_queries": { de: "Queries", en: "Queries" },
  "settings.referral": { de: "Empfehlen & sparen", en: "Refer & save" },
  "settings.referral_desc": {
    de: "Du bekommst 1 Monat gratis pro geworbenem Kunden — der Geworbene auch.",
    en: "You get 1 month free per referred customer — so do they.",
  },
  "settings.referral_info": {
    de: "12 Empfehlungen = ein Gratisjahr. Keine Obergrenze.",
    en: "12 referrals = one free year. No limit.",
  },
  "settings.referral_so_far": { de: "Bisher geworben:", en: "Referred so far:" },
  "settings.referral_loading": {
    de: "Empfehlungslink wird geladen…",
    en: "Loading referral link…",
  },
  "settings.partner_link": {
    de: "Mehr verdienen? Zum Partnerprogramm (30 % wiederkehrend)",
    en: "Earn more? Partner program (30% recurring)",
  },
  "settings.data_export": { de: "Datenexport (DSGVO)", en: "Data export (GDPR)" },
  "settings.data_export_desc": {
    de: "Alle deine Daten — Konto, Nutzung und das komplette Brain (Akten, Dokumente, Fristen) — als JSON-Datei (Art. 20 DSGVO).",
    en: "All your data — account, usage and the complete brain (cases, documents, deadlines) — as a JSON file (Art. 20 GDPR).",
  },
  "settings.export_button": { de: "Daten exportieren ↓", en: "Export data ↓" },
  "settings.tab_scim": { de: "SCIM", en: "SCIM" },
  "settings.scim_title": { de: "SCIM Directory Sync", en: "SCIM Directory Sync" },
  "settings.scim_desc": {
    de: "Automatische Benutzerbereitstellung über Identity Provider (WorkOS)",
    en: "Automated user provisioning via Identity Provider (WorkOS)",
  },
  "settings.scim_endpoint": { de: "SCIM-Endpoint", en: "SCIM endpoint" },
  "settings.scim_endpoint_desc": {
    de: "URL für die Konfiguration im Identity Provider",
    en: "URL for configuration in the Identity Provider",
  },
  "settings.scim_features": { de: "Features", en: "Features" },
  "settings.scim_features_desc": {
    de: "Automatisierte Benutzerverwaltung",
    en: "Automated user management",
  },
  "settings.scim_feature_1": {
    de: "Auto-Provisioning: Neue IdP-Benutzer werden automatisch erstellt",
    en: "Auto-provisioning: New IdP users are created automatically",
  },
  "settings.scim_feature_2": {
    de: "Auto-Deprovisioning: Gelöschte Benutzer werden deaktiviert (Audit-Trail erhalten)",
    en: "Auto-deprovisioning: Deleted users are deactivated (audit trail preserved)",
  },
  "settings.scim_feature_3": {
    de: "Gruppen-Sync: AD/LDAP-Gruppen werden synchronisiert",
    en: "Group sync: AD/LDAP groups are synchronized",
  },
  "settings.scim_feature_4": {
    de: "Manuelle Synchronisation verfügbar",
    en: "Manual synchronization available",
  },
  "settings.scim_manage": { de: "Verwaltung", en: "Management" },
  "settings.scim_manage_desc": {
    de: "Vollständige SCIM-Konfiguration und Sync-Log",
    en: "Full SCIM configuration and sync log",
  },
  "settings.scim_manage_button": { de: "SCIM verwalten →", en: "Manage SCIM →" },
  "settings.tls": { de: "TLS", en: "TLS" },
  "settings.per_hour_short": { de: "€/h", en: "€/h" },
  "settings.rvg_info": {
    de: "RVG-Gebühren werden automatisch nach der deutschen Rechtsanwaltsvergütungsordnung berechnet. Stundensatz ist nur für Beratungen relevant.",
    en: "RVG fees are automatically calculated according to the German Lawyers' Remuneration Act. Hourly rate is only relevant for consultations.",
  },
  "settings.ratg_info": {
    de: "RATG-Gebühren werden automatisch nach der österreichischen Rechtsanwaltstarifordnung berechnet. Stundensatz ist nur für Beratungen relevant.",
    en: "RATG fees are automatically calculated according to the Austrian Lawyers' Tariff Act. Hourly rate is only relevant for consultations.",
  },

  // ── Layout ──
  "layout.skip_to_content": { de: "Zum Inhalt springen", en: "Skip to content" },

  // ── Sidebar: additional nav items ──
  "nav.playbooks": { de: "Playbooks", en: "Playbooks" },
  "nav.ai_model": { de: "KI-Modell", en: "AI Model" },

  // ── Topbar: additional strings ──
  "topbar.close_menu": { de: "Menü schließen", en: "Close menu" },
  "topbar.unread_count": { de: "ungelesene Benachrichtigungen", en: "unread notifications" },
  "topbar.keyboard_shortcuts": { de: "Tastaturkürzel", en: "Keyboard shortcuts" },
  "topbar.profile": { de: "Profil", en: "Profile" },
  "topbar.mark_all_read": { de: "Alle als gelesen markieren", en: "Mark all as read" },

  // ── Onboarding wizard ──
  "onboarding.title": { de: "Willkommen bei Subsumio", en: "Welcome to Subsumio" },
  "onboarding.subtitle": {
    de: "In 3 Schritten zum einsatzbereiten Kanzlei-Brain",
    en: "3 steps to your ready-to-use firm brain",
  },
  "onboarding.step": { de: "Schritt", en: "Step" },
  "onboarding.of": { de: "von", en: "of" },
  "onboarding.skip": { de: "Überspringen", en: "Skip" },
  "onboarding.next": { de: "Weiter", en: "Next" },
  "onboarding.back": { de: "Zurück", en: "Back" },
  "onboarding.finish": { de: "Fertig — Dashboard öffnen", en: "Finish — Open dashboard" },
  "onboarding.step_welcome": { de: "Willkommen", en: "Welcome" },
  "onboarding.step_welcome_desc": {
    de: "Dein Kanzlei-Brain wird gleich einsatzbereit sein. Lass uns kurz einrichten, was du brauchst.",
    en: "Your firm brain will be ready in a moment. Let's quickly set up what you need.",
  },
  "onboarding.step_industry": { de: "Branche wählen", en: "Choose industry" },
  "onboarding.step_industry_desc": {
    de: "Wir personalisieren dein Dashboard und Brain-Schema basierend auf deiner Praxis.",
    en: "We personalize your dashboard and brain schema based on your practice.",
  },
  "onboarding.step_upload": { de: "Erstes Dokument", en: "First document" },
  "onboarding.step_upload_desc": {
    de: "Lade eine Akte, ein Urteil oder ein PDF hoch — wir indexieren und verknüpfen es sofort.",
    en: "Upload a case file, judgment or PDF — we index and link it instantly.",
  },
  "onboarding.step_upload_drop": {
    de: "Datei hierher ziehen oder klicken zum Auswählen",
    en: "Drag a file here or click to select",
  },
  "onboarding.step_upload_hint": {
    de: "PDF, DOCX, MD oder TXT — max. 50 MB",
    en: "PDF, DOCX, MD or TXT — max 50 MB",
  },
  "onboarding.step_upload_success": {
    de: "Hochgeladen und indexiert!",
    en: "Uploaded and indexed!",
  },
  "onboarding.step_query": { de: "Erste Frage", en: "First question" },
  "onboarding.step_query_desc": {
    de: "Stelle eine Frage zu deinem Brain. Die KI antwortet mit Fundstellen.",
    en: "Ask a question about your brain. AI answers with citations.",
  },
  "onboarding.step_query_placeholder": {
    de: "z.B. Was ist der aktuelle Stand in Akte Meier?",
    en: "e.g. What's the current status of the Meier case?",
  },
  "onboarding.step_query_ask": { de: "Fragen", en: "Ask" },
  "onboarding.step_query_thinking": { de: "Denke nach…", en: "Thinking…" },
  "onboarding.step_done": { de: "Fertig!", en: "Done!" },
  "onboarding.step_done_desc": {
    de: "Dein Kanzlei-Brain ist einsatzbereit. Du kannst jederzeit Dokumente nachladen und Fragen stellen.",
    en: "Your firm brain is ready. You can upload more documents and ask questions anytime.",
  },
  "onboarding.industry_legal": { de: "Kanzlei / Rechtsabteilung", en: "Law firm / legal team" },
  "onboarding.industry_other": { de: "Andere", en: "Other" },
  "onboarding.error_upload": {
    de: "Upload fehlgeschlagen. Bitte erneut versuchen.",
    en: "Upload failed. Please try again.",
  },
  "onboarding.error_query": {
    de: "Frage konnte nicht gesendet werden. Bitte erneut versuchen.",
    en: "Failed to send question. Please try again.",
  },
} satisfies Record<string, BiString>;

export type DashboardKey = keyof typeof D;

// ── t() factory ──────────────────────────────────────────────────────────────

export function createT(lang: Lang) {
  return (key: DashboardKey): string => {
    const entry = D[key];
    if (!entry) return key;
    return entry[lang] ?? entry.de;
  };
}

export type TFunc = ReturnType<typeof createT>;
