/**
 * AT judikatur (OGH) retrieval gold set — PENDING REVIEW (draft questions).
 *
 * Generated by server/scripts/draft-judikatur-gold-questions.ts from the
 * real at-judikatur/ RIS Rechtssatz corpus. Every file existence-checked.
 *
 * LEAKAGE RULE: no query contains the target decision's Geschäftszahl
 * (case number) or ECLI — queries are built from the Rechtssatz legal-
 * principle text + the interpreted statute's abbreviation, never the
 * decision's own citation.
 *
 * Review workflow (matches server/test/fixtures/retrieval-quality/legal-at/
 * pending-review.ts): review each entry, set reviewed_by + reviewed_at,
 * then move approved entries into corpus.ts's JUDIKATUR_GOLD.
 *
 * DO NOT move entries to the gold set without reviewed_by + reviewed_at.
 */

export interface JudikaturDraftEntry {
  query: string;
  fileBase: string;
  caseNumber: string;
  legalArea: string;
  normAbbr: string;
  status: "draft" | "reviewed";
  reviewed_by?: string;
  reviewed_at?: string;
}

export const JUDIKATUR_PENDING: JudikaturDraftEntry[] = [
  {
    query:
      "OGH Verhaltensvorschrift Verletzungshandlung Interessenabwägung Zurechnungsgrundes ABGB",
    fileBase: "2025-04-29-8ob127-02p",
    caseNumber: "8Ob127/02p",
    legalArea: "Zivilrecht",
    normAbbr: "ABGB",
    status: "draft",
  },
  {
    query: "OGH Kollektivvertrages eigentümlichen angehörenden Bestimmungen ABGB",
    fileBase: "2025-08-12-4ob50-74",
    caseNumber: "4Ob50/74",
    legalArea: "Zivilrecht",
    normAbbr: "ABGB",
    status: "draft",
  },
  {
    query: "OGH Verjährungsfrist anzuwendenden eingelangte rechtzeitig ABGB",
    fileBase: "2024-12-12-2ob213-77",
    caseNumber: "2Ob213/77",
    legalArea: "Zivilrecht",
    normAbbr: "ABGB",
    status: "draft",
  },
  {
    query: "OGH Gewaltanwendung eingeklemmt Handtasche getragene StGB",
    fileBase: "2026-05-06-2os783-48",
    caseNumber: "2Os783/48",
    legalArea: "Strafrecht",
    normAbbr: "StGB",
    status: "draft",
  },
  {
    query: "OGH generalisierenden Untauglichkeit Verwirklichung Besonderheiten StGB",
    fileBase: "2021-09-29-11os114-95",
    caseNumber: "11Os114/95",
    legalArea: "Strafrecht",
    normAbbr: "StGB",
    status: "draft",
  },
  {
    query:
      "OGH Strafverfolgungsinteresses Vermögensbekenntnisses Vermögensinteressen Verfahrenshilfe StGB",
    fileBase: "2023-01-24-12os24-08h",
    caseNumber: "12Os24/08h",
    legalArea: "Strafrecht",
    normAbbr: "StGB",
    status: "draft",
  },
  {
    query:
      "OGH tatbestandsrelevanten Treibstoffdiebstahl Bodenverunreinigung Privatbeteiligter StPO",
    fileBase: "2018-04-20-14os45-96",
    caseNumber: "14Os45/96",
    legalArea: "Zivilrecht",
    normAbbr: "StPO",
    status: "draft",
  },
  {
    query: "OGH Vollmachtsauflösung Rechtsmittelfrist bevollmächtigte bekanntgegeben StPO",
    fileBase: "2026-03-24-11os120-87-11os121-87",
    caseNumber: "11Os120/87 (11Os121/87)",
    legalArea: "Strafrecht",
    normAbbr: "StPO",
    status: "draft",
  },
  {
    query: "OGH zuständigkeitsbegründend Rechtswirksamkeit Hauptverfahren Landesgerichts StPO",
    fileBase: "2026-06-16-11ns29-18f",
    caseNumber: "11Ns29/18f",
    legalArea: "Strafrecht",
    normAbbr: "StPO",
    status: "draft",
  },
  {
    query: "OGH Verbands-Musterklagen rechtswirksam Gegenstand abgetreten ZPO",
    fileBase: "2025-07-23-7ob85-07m",
    caseNumber: "7Ob85/07m",
    legalArea: "Zivilrecht",
    normAbbr: "ZPO",
    status: "draft",
  },
  {
    query: "OGH Verfassungswidrigkeit Masseverwalters entscheidet Bestimmung ZPO",
    fileBase: "2026-04-22-8ob28-05h",
    caseNumber: "8Ob28/05h",
    legalArea: "Zivilrecht",
    normAbbr: "ZPO",
    status: "draft",
  },
  {
    query: "OGH Revisionsbeantwortung zweckentsprechenden Rechtsverteidigung Unzulässigkeit ZPO",
    fileBase: "2026-06-23-4ob189-99v",
    caseNumber: "4Ob189/99v",
    legalArea: "Zivilrecht",
    normAbbr: "ZPO",
    status: "draft",
  },
  {
    query: "OGH Impugnationsstreit rechtsbegründenden Exekutionsantrag Rechtsstandpunkt EO",
    fileBase: "2025-11-26-3ob80-84",
    caseNumber: "3Ob80/84",
    legalArea: "Zivilrecht",
    normAbbr: "EO",
    status: "draft",
  },
  {
    query: "OGH Sachverständigen vertragsmäßige Paragraphen demjenigen EO",
    fileBase: "2026-04-22-2ob226-27",
    caseNumber: "2Ob226/27",
    legalArea: "Zivilrecht",
    normAbbr: "EO",
    status: "draft",
  },
  {
    query: "OGH Privatankläger Hereinbringung geschlossenen Strafrichter EO",
    fileBase: "2025-04-11-3ob526-30",
    caseNumber: "3Ob526/30",
    legalArea: "Zivilrecht",
    normAbbr: "EO",
    status: "draft",
  },
  {
    query: "OGH Vorbereitungsgeschäfte unternehmensbezogene Geschäftsbetriebs unternehmerische UGB",
    fileBase: "2024-04-23-6ob203-11p",
    caseNumber: "6Ob203/11p",
    legalArea: "Zivilrecht",
    normAbbr: "UGB",
    status: "draft",
  },
  {
    query: "OGH Sacheinlageprüfberichts Sacheinlageprüfer Verlässlichkeit ersatzpflichtig UGB",
    fileBase: "2025-06-04-6ob196-24b",
    caseNumber: "6Ob196/24b",
    legalArea: "Zivilrecht",
    normAbbr: "UGB",
    status: "draft",
  },
  {
    query: "OGH Unternehmensübergang Haftungsausschluss Publizitätsakt Zusammenhang UGB",
    fileBase: "2024-08-20-6r201-24h",
    caseNumber: "6R201/24h",
    legalArea: "Zivilrecht",
    normAbbr: "UGB",
    status: "draft",
  },
  {
    query: "OGH Lebensgemeinschaft Erscheinungsbild Zusammenlebens nichteheliche ASVG",
    fileBase: "2024-08-13-10obs276-90",
    caseNumber: "10ObS276/90",
    legalArea: "Zivilrecht",
    normAbbr: "ASVG",
    status: "draft",
  },
  {
    query: "OGH Fahrlässigkeit gröblichster gleichsetzen Paragraph ASVG",
    fileBase: "2021-10-22-4ob72-69",
    caseNumber: "4Ob72/69",
    legalArea: "Zivilrecht",
    normAbbr: "ASVG",
    status: "draft",
  },
  {
    query: "OGH Arbeitslosigkeit Rahmenzeitraum Berufsschutzes verlängern ASVG",
    fileBase: "2019-07-30-10obs8-15x",
    caseNumber: "10ObS8/15x",
    legalArea: "Zivilrecht",
    normAbbr: "ASVG",
    status: "draft",
  },
  {
    query: "OGH Privilegierungsverbot Betriebsinhaber zurückgefordert Vergangenheit ArbVG",
    fileBase: "2025-03-19-9oba96-24v",
    caseNumber: "9ObA96/24v",
    legalArea: "Zivilrecht",
    normAbbr: "ArbVG",
    status: "draft",
  },
  {
    query: "OGH betriebsverfassungsrechtlich Arbeitnehmergruppe Verständigung Betriebsrates ArbVG",
    fileBase: "2025-02-27-4ob51-85",
    caseNumber: "4Ob51/85",
    legalArea: "Zivilrecht",
    normAbbr: "ArbVG",
    status: "draft",
  },
  {
    query: "OGH vorgeschriebene beabsichtigten Verständigung Betriebsrates ArbVG",
    fileBase: "2025-12-18-9oba255-90",
    caseNumber: "9ObA255/90",
    legalArea: "Zivilrecht",
    normAbbr: "ArbVG",
    status: "draft",
  },
  {
    query: "OGH Wiederholungsgefahr Willensrichtung Rechtsstreites Anhaltspunkte KSchG",
    fileBase: "2023-10-23-4ob330-65",
    caseNumber: "4Ob330/65",
    legalArea: "Zivilrecht",
    normAbbr: "KSchG",
    status: "draft",
  },
  {
    query:
      "OGH Gewährleistungshinweise Geschäftsbedingungen Regelungsbereiche Betrachtungsweise KSchG",
    fileBase: "2026-03-18-6ob140-06s",
    caseNumber: "6Ob140/06s",
    legalArea: "Zivilrecht",
    normAbbr: "KSchG",
    status: "draft",
  },
  {
    query: "OGH rechtsmissbräuchliche Vertragsklauseln Transparenzgebot EU-Richtlinie KSchG",
    fileBase: "2026-03-18-6ob160-00y",
    caseNumber: "6Ob160/00y",
    legalArea: "Zivilrecht",
    normAbbr: "KSchG",
    status: "draft",
  },
  {
    query: "OGH Gemeinschaftsanlage Beteiligung Kriterium rechtlich MRG",
    fileBase: "2026-01-29-5ob74-87",
    caseNumber: "5Ob74/87",
    legalArea: "Zivilrecht",
    normAbbr: "MRG",
    status: "draft",
  },
  {
    query: "OGH Fruchtgenussrecht Bestandgeber Mietvertrags Fruchtnießer MRG",
    fileBase: "2026-03-12-4ob595-87",
    caseNumber: "4Ob595/87",
    legalArea: "Zivilrecht",
    normAbbr: "MRG",
    status: "draft",
  },
  {
    query: "OGH Vertragsaufhebungserklärung Beschlußfassung Zinsrückstand geschuldete MRG",
    fileBase: "2026-03-25-6ob696-88",
    caseNumber: "6Ob696/88",
    legalArea: "Zivilrecht",
    normAbbr: "MRG",
    status: "draft",
  },
  {
    query: "OGH Berufungsgericht festgestellten Vorinstanzen Sachverhalt AußStrG",
    fileBase: "2021-01-28-1ob27-90-1ob28-90",
    caseNumber: "1Ob27/90 (1Ob28/90)",
    legalArea: "Zivilrecht",
    normAbbr: "AußStrG",
    status: "draft",
  },
  {
    query:
      "OGH materiell-rechtlichen vermögensrechtlicher vermögensrechtliche Vermögensrechte AußStrG",
    fileBase: "2025-12-18-6ob521-91",
    caseNumber: "6Ob521/91",
    legalArea: "Zivilrecht",
    normAbbr: "AußStrG",
    status: "draft",
  },
  {
    query: "OGH Rechtsmittelfrist unzuständigen Rechtsmittel einzurechnen AußStrG",
    fileBase: "2025-12-16-2ob21-55",
    caseNumber: "2Ob21/55",
    legalArea: "Zivilrecht",
    normAbbr: "AußStrG",
    status: "draft",
  },
  {
    query:
      "OGH Rechtsverfolgungskosten eigenkapitalersetzenden Gesellschafterleistung Zweckentsprechende IO",
    fileBase: "2026-02-24-6ob237-24g",
    caseNumber: "6Ob237/24g",
    legalArea: "Zivilrecht",
    normAbbr: "IO",
    status: "draft",
  },
  {
    query: "OGH Anfechtungsanspruch Insolvenzeröffnung angriffsweise „erlöschen“ IO",
    fileBase: "2025-10-07-17ob12-25a",
    caseNumber: "17Ob12/25a",
    legalArea: "Zivilrecht",
    normAbbr: "IO",
    status: "draft",
  },
  {
    query: "OGH Insolvenzeröffnung Insolvenzforderung Haftungsbescheid aufschiebend IO",
    fileBase: "2019-12-05-17ob7-19g",
    caseNumber: "17Ob7/19g",
    legalArea: "Zivilrecht",
    normAbbr: "IO",
    status: "draft",
  },
];
