#!/usr/bin/env tsx
/**
 * CI guard: docs/STATUS.md must stay fresh — the verification block is
 * generated by `bun run status`; if it is older than 45 days the doc
 * likely drifts from the codebase. Fails the build in that case.
 */

import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const DOC = resolve(process.cwd(), "docs/STATUS.md");
const MAX_AGE_DAYS = 45;

const doc = readFileSync(DOC, "utf8");
const m = doc.match(/Generiert von `bun run status` am (\d{4}-\d{2}-\d{2})/);
if (!m) {
  console.error(
    "[check-status-fresh] Kein generierter Verifikations-Block gefunden — " +
      "einmal `bun run status` laufen lassen."
  );
  process.exit(1);
}

const ageMs = Date.now() - Date.parse(m[1]);
const ageDays = Math.floor(ageMs / 86_400_000);
if (ageDays > MAX_AGE_DAYS) {
  console.error(
    `[check-status-fresh] docs/STATUS.md ist ${ageDays} Tage alt ` +
      `(>${MAX_AGE_DAYS}). Bitte \`bun run status\` ausführen und committen.`
  );
  process.exit(1);
}
console.log(`[check-status-fresh] STATUS.md ist ${ageDays} Tage alt — ok`);
