-- Migration 004: Legal Commentaries — Synthetic + Open-Access
--
-- Tables: legal_commentaries, legal_commentary_chunks
-- Features: pgvector HNSW, tsvector BM25, §-level commentary, treatment summary
--
-- Architecture:
-- - Synthetic commentaries are generated by the legal_commentary_synthesis
--   dream cycle phase from linked judgements per statute section
-- - Open-access commentaries are ingested from RIS-OGD (AT), openlegaldata (DE)
-- - Both types share the same table, distinguished by commentary_type
-- - Commentary chunks are embedded and searchable via hybrid search
-- - Treatment summary aggregates good_law/bad_law/at_risk from linked cases

-- ============================================================
-- legal_commentaries: §-level commentary (synthetic + open-access)
-- ============================================================
CREATE TABLE IF NOT EXISTS subsumio_legal_commentaries (
  id              TEXT PRIMARY KEY,          -- e.g. "de/bgb/§-823" or "at/abgb/§-1311"
  jurisdiction    TEXT NOT NULL,             -- de, at, ch, eu
  statute_abbr    TEXT NOT NULL,             -- BGB, ABGB, OR, ZGB
  section_num     TEXT NOT NULL,             -- "823", "1311", "Art-41"
  commentary_type TEXT NOT NULL,             -- synthetic, open_access
  title           TEXT NOT NULL,             -- e.g. "§ 823 BGB — Schadensersatzpflicht"
  content         TEXT NOT NULL,             -- Markdown commentary text
  statute_text    TEXT,                      -- Original statute text for reference
  source_model    TEXT,                      -- "deepseek-v3.2" for synthetic
  source_url      TEXT,                      -- URL for open_access
  source_name     TEXT,                      -- "RIS-OGD", "openlegaldata", "subsumio-synthetic"
  case_count      INTEGER NOT NULL DEFAULT 0,-- Number of linked judgements
  linked_cases    TEXT[],                    -- Array of judgement IDs
  treatment_summary JSONB,                  -- {good_law, bad_law, at_risk, mixed, unknown}
  key_holdings    TEXT[],                    -- Extracted key legal principles
  keywords        TEXT[],                    -- Schlagworte
  language        TEXT NOT NULL DEFAULT 'de',
  content_hash    TEXT,                      -- For change detection
  generated_at    TIMESTAMPTZ,               -- When synthetic was generated
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  embedded_at     TIMESTAMPTZ,
  search_vector   TSVECTOR
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_commentaries_jurisdiction ON subsumio_legal_commentaries(jurisdiction);
CREATE INDEX IF NOT EXISTS idx_commentaries_statute ON subsumio_legal_commentaries(statute_abbr);
CREATE INDEX IF NOT EXISTS idx_commentaries_section ON subsumio_legal_commentaries(section_num);
CREATE INDEX IF NOT EXISTS idx_commentaries_type ON subsumio_legal_commentaries(commentary_type);
CREATE INDEX IF NOT EXISTS idx_commentaries_statute_section ON subsumio_legal_commentaries(statute_abbr, section_num);
CREATE INDEX IF NOT EXISTS idx_commentaries_search_vector ON subsumio_legal_commentaries USING GIN(search_vector);
CREATE INDEX IF NOT EXISTS idx_commentaries_keywords ON subsumio_legal_commentaries USING GIN(keywords);
CREATE INDEX IF NOT EXISTS idx_commentaries_treatment ON subsumio_legal_commentaries USING GIN(treatment_summary);

-- ============================================================
-- legal_commentary_chunks: Embedded chunks for vector search
-- ============================================================
CREATE TABLE IF NOT EXISTS subsumio_legal_commentary_chunks (
  id              SERIAL PRIMARY KEY,
  commentary_id   TEXT NOT NULL REFERENCES subsumio_legal_commentaries(id) ON DELETE CASCADE,
  chunk_index     INTEGER NOT NULL,
  chunk_text      TEXT NOT NULL,
  chunk_type      TEXT NOT NULL DEFAULT 'commentary', -- commentary, statute_text, key_holdings
  embedding       vector(1024),
  embedding_model TEXT NOT NULL DEFAULT 'multilingual-e5-large',
  token_count     INTEGER,
  embedded_at     TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_cchunks_commentary_idx ON subsumio_legal_commentary_chunks(commentary_id, chunk_index);
CREATE INDEX IF NOT EXISTS idx_cchunks_commentary ON subsumio_legal_commentary_chunks(commentary_id);
CREATE INDEX IF NOT EXISTS idx_cchunks_embedding ON subsumio_legal_commentary_chunks USING hnsw (embedding vector_cosine_ops);
CREATE INDEX IF NOT EXISTS idx_cchunks_stale ON subsumio_legal_commentary_chunks(commentary_id, chunk_index) WHERE embedding IS NULL;
CREATE INDEX IF NOT EXISTS idx_cchunks_type ON subsumio_legal_commentary_chunks(chunk_type);

-- ============================================================
-- Full-text search trigger for commentaries
-- ============================================================
CREATE OR REPLACE FUNCTION subsumio_commentary_search_vector_fn() RETURNS trigger AS $func$
BEGIN
  NEW.search_vector :=
    setweight(to_tsvector('german', coalesce(NEW.title, '')), 'A') ||
    setweight(to_tsvector('german', coalesce(NEW.content, '')), 'B') ||
    setweight(to_tsvector('german', coalesce(array_to_string(NEW.key_holdings, ' '), '')), 'B') ||
    setweight(to_tsvector('german', coalesce(array_to_string(NEW.keywords, ' '), '')), 'C');
  NEW.updated_at := now();
  RETURN NEW;
END;
$func$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS subsumio_commentary_search_vector_trg ON subsumio_legal_commentaries;
CREATE TRIGGER subsumio_commentary_search_vector_trg
  BEFORE INSERT OR UPDATE ON subsumio_legal_commentaries
  FOR EACH ROW
  EXECUTE FUNCTION subsumio_commentary_search_vector_fn();
