import { createHandler, apiError } from "@/lib/api-handler";
import { ENGINE_URL } from "@/lib/engine";
import { logger } from "@/lib/logger";

const log = logger("api/legal/deep-analysis/run");

export const dynamic = "force-dynamic";

/** Run ids are generated by the engine: timestamp + uuid fragment. */
const ID_RE = /^[A-Za-z0-9-]{1,80}$/;

/** Status poll for a background deep analysis. No credits: polling is free. */
export const GET = createHandler(
  { action: "legal.deep_analysis", rateTier: "standard" },
  async (ctx, _body, _query, req) => {
    const { id } = await (req as unknown as { params: Promise<{ id: string }> }).params;
    if (!ID_RE.test(id ?? "")) return apiError("invalid_id", "Ungültige Lauf-Kennung", 400);
    try {
      const upstream = await fetch(
        `${ENGINE_URL}/api/legal/deep-analysis/run/deep_analysis/${encodeURIComponent(id)}`,
        { headers: ctx.headers, signal: AbortSignal.timeout(15_000) }
      );
      const payload = (await upstream.json().catch(() => ({}))) as Record<string, unknown>;
      if (!upstream.ok) {
        return Response.json(payload.error ? payload : { error: `Engine ${upstream.status}` }, {
          status: upstream.status,
        });
      }
      return Response.json(payload);
    } catch (err) {
      log.error(
        "[deep-analysis/run] engine unreachable:",
        err instanceof Error ? err.message : err
      );
      return apiError("service_unavailable", "Engine nicht erreichbar", 503);
    }
  }
);
