// GENERATED by scripts/ratg/generate-tariff.mjs — do not edit by hand.
// Source: Rechtsanwaltstarifgesetz (RATG), Anl. 1, BGBl. Nr. 189/1969 zuletzt geändert durch BGBl. I Nr. 85/2024
// Valorised amounts: BGBl. II Nr. 131/2023, in force from 1 May 2023.
// RIS: https://ris.bka.gv.at/eli/bgbl/1969/189/ANL1/NOR40263879 (retrieved 2026-08-05)

export const RATG_TARIFF_SOURCE = {
  statute: "Rechtsanwaltstarifgesetz (RATG)",
  version: "BGBl. Nr. 189/1969 zuletzt geändert durch BGBl. I Nr. 85/2024",
  valorisation: "BGBl. II Nr. 131/2023, ab 1. Mai 2023",
  valorisedFrom: "2023-05-01",
  eli: "https://ris.bka.gv.at/eli/bgbl/1969/189/ANL1/NOR40263879",
  retrievedAt: "2026-08-05",
} as const;

export interface RatgTariffBlock {
  bands: { upTo: number; amount: number }[];
  stepEvery: number;
  stepAmount: number;
  stepFrom: number;
  stepTo: number;
  extraStepTo: number;
  permille: { over: number; rate: number }[];
  cap: number;
  /** Cap for each further (half-rated) hour of a hearing, where the item has hearings. */
  hourCap: number | null;
}

export const RATG_TARIFF: Record<"TP1" | "TP2" | "TP3A" | "TP3B" | "TP3C", RatgTariffBlock> = {
  TP1: {
    bands: [
      {
        upTo: 40,
        amount: 4.2,
      },
      {
        upTo: 70,
        amount: 5.9,
      },
      {
        upTo: 110,
        amount: 7.5,
      },
      {
        upTo: 180,
        amount: 8.4,
      },
      {
        upTo: 360,
        amount: 9.2,
      },
      {
        upTo: 730,
        amount: 11.1,
      },
      {
        upTo: 1090,
        amount: 14.8,
      },
      {
        upTo: 1820,
        amount: 16.1,
      },
      {
        upTo: 3630,
        amount: 17.9,
      },
      {
        upTo: 5450,
        amount: 21.5,
      },
      {
        upTo: 7270,
        amount: 26.6,
      },
      {
        upTo: 10170,
        amount: 35.1,
      },
    ],
    stepEvery: 1450,
    stepAmount: 4.2,
    stepFrom: 10170,
    stepTo: 34820,
    extraStepTo: 36340,
    permille: [
      {
        over: 36340,
        rate: 0.0001,
      },
      {
        over: 363360,
        rate: 0.00005,
      },
    ],
    cap: 312.2,
    hourCap: null,
  },
  TP2: {
    bands: [
      {
        upTo: 40,
        amount: 17.9,
      },
      {
        upTo: 70,
        amount: 26.6,
      },
      {
        upTo: 110,
        amount: 35.1,
      },
      {
        upTo: 180,
        amount: 38.7,
      },
      {
        upTo: 360,
        amount: 43.7,
      },
      {
        upTo: 730,
        amount: 52.5,
      },
      {
        upTo: 1090,
        amount: 69.8,
      },
      {
        upTo: 1820,
        amount: 78.6,
      },
      {
        upTo: 3630,
        amount: 87,
      },
      {
        upTo: 5450,
        amount: 104.6,
      },
      {
        upTo: 7270,
        amount: 130.2,
      },
      {
        upTo: 10170,
        amount: 173.8,
      },
    ],
    stepEvery: 1450,
    stepAmount: 17.9,
    stepFrom: 10170,
    stepTo: 34820,
    extraStepTo: 36340,
    permille: [
      {
        over: 36340,
        rate: 0.0005,
      },
      {
        over: 363360,
        rate: 0.00025,
      },
    ],
    cap: 1558.2,
    hourCap: 779.3,
  },
  TP3A: {
    bands: [
      {
        upTo: 40,
        amount: 35.1,
      },
      {
        upTo: 70,
        amount: 52.5,
      },
      {
        upTo: 110,
        amount: 69.8,
      },
      {
        upTo: 180,
        amount: 76.8,
      },
      {
        upTo: 360,
        amount: 87,
      },
      {
        upTo: 730,
        amount: 104.6,
      },
      {
        upTo: 1090,
        amount: 139.1,
      },
      {
        upTo: 1820,
        amount: 156.2,
      },
      {
        upTo: 3630,
        amount: 173.8,
      },
      {
        upTo: 5450,
        amount: 208.2,
      },
      {
        upTo: 7270,
        amount: 260.2,
      },
      {
        upTo: 10170,
        amount: 346.6,
      },
    ],
    stepEvery: 1450,
    stepAmount: 35.1,
    stepFrom: 10170,
    stepTo: 34820,
    extraStepTo: 36340,
    permille: [
      {
        over: 36340,
        rate: 0.001,
      },
      {
        over: 363360,
        rate: 0.0005,
      },
    ],
    cap: 20770.6,
    hourCap: 10385.4,
  },
  TP3B: {
    bands: [
      {
        upTo: 40,
        amount: 43.7,
      },
      {
        upTo: 70,
        amount: 65.4,
      },
      {
        upTo: 110,
        amount: 87,
      },
      {
        upTo: 180,
        amount: 96,
      },
      {
        upTo: 360,
        amount: 108.6,
      },
      {
        upTo: 730,
        amount: 130.2,
      },
      {
        upTo: 1090,
        amount: 173.8,
      },
      {
        upTo: 1820,
        amount: 195.2,
      },
      {
        upTo: 3630,
        amount: 216.9,
      },
      {
        upTo: 5450,
        amount: 260.2,
      },
      {
        upTo: 7270,
        amount: 325,
      },
      {
        upTo: 10170,
        amount: 433.2,
      },
    ],
    stepEvery: 1450,
    stepAmount: 43.7,
    stepFrom: 10170,
    stepTo: 34820,
    extraStepTo: 36340,
    permille: [
      {
        over: 36340,
        rate: 0.00125,
      },
      {
        over: 363360,
        rate: 0.000625,
      },
    ],
    cap: 25963.2,
    hourCap: 12981.8,
  },
  TP3C: {
    bands: [
      {
        upTo: 40,
        amount: 52.5,
      },
      {
        upTo: 70,
        amount: 78.6,
      },
      {
        upTo: 110,
        amount: 104.6,
      },
      {
        upTo: 180,
        amount: 115,
      },
      {
        upTo: 360,
        amount: 130.2,
      },
      {
        upTo: 730,
        amount: 156.2,
      },
      {
        upTo: 1090,
        amount: 208.2,
      },
      {
        upTo: 1820,
        amount: 234.4,
      },
      {
        upTo: 3630,
        amount: 260.2,
      },
      {
        upTo: 5450,
        amount: 312.2,
      },
      {
        upTo: 7270,
        amount: 390,
      },
      {
        upTo: 10170,
        amount: 519.6,
      },
    ],
    stepEvery: 1450,
    stepAmount: 52.5,
    stepFrom: 10170,
    stepTo: 34820,
    extraStepTo: 36340,
    permille: [
      {
        over: 36340,
        rate: 0.0015,
      },
      {
        over: 363360,
        rate: 0.00075,
      },
    ],
    cap: 31155.8,
    hourCap: 15578,
  },
};
